- docs/products/redis/howto/migrate-aiven-redis.md
- docs/products/redis/howto/migrate-redis-aiven-via-console.md
Add notice about Redis versions when migrating.
> update(Redis): version requirements for migration

- docs/platform/howto/billing-assign-projects.md
Update instructions for assigning projects to billing groups to reflect changes in the UI.
> update(billing): update instructions for assigning projects to billing groups

- .vscode/aiven.code-snippets
Adds a snippet for inserting a section into docs indicating what permissions are needed to access a feature.
> feat: required access snippet

- .vscode/aiven.code-snippets
https://aiven.atlassian.net/browse/DOC-799
> feat(code-snippet): prerequisites section

- docs/products/dragonfly.md
- docs/products/dragonfly/concepts/ha-dragonfly.md
- docs/products/dragonfly/concepts/overview.md
- docs/products/dragonfly/get-started.md
- docs/products/dragonfly/howto/migrate-aiven-redis-df-console.md
- docs/products/dragonfly/howto/migrate-ext-redis-df-console.md
- docs/products/flink/concepts/custom-jars.md
- docs/products/flink/howto/create-jar-application.md
- docs/products/kafka/concepts/consumer-lag-predictor.md
- docs/products/kafka/concepts/kafka-quotas.md
- docs/products/kafka/concepts/kafka-tiered-storage.md
- docs/products/kafka/concepts/list-kafka-tiered-storage.md
- docs/products/kafka/concepts/tiered-storage-guarantees.md
- docs/products/kafka/concepts/tiered-storage-how-it-works.md
- docs/products/kafka/concepts/tiered-storage-limitations.md
- docs/products/kafka/howto/configure-topic-tiered-storage.md
- docs/products/kafka/howto/enable-kafka-tiered-storage.md
- docs/products/kafka/howto/enabled-consumer-lag-predictor.md
- docs/products/kafka/howto/tiered-storage-overview-page.md
> update(services): updated EA and LA badges

- docs/platform/howto/saml/add-google-idp.md
- sidebars.ts
Add parameter to configure IdP-initiated login for Google IdP.
> update(auth): add parameter for Google IdP

- docs/platform/concepts/managed-users.md
Add info on how to deactivate managed users in an org.
> add(platform): instructions for deactivating users

- docs/platform/howto/add-project-members.md
- sidebars.ts
New set of instructions for adding users to projects.
> add(platform): instructions for project members

- docs/platform/concepts/hourly-billing-model.md
- docs/platform/howto/billing-assign-projects.md
- docs/platform/howto/create-billing-groups.md
- docs/platform/howto/manage-payment-card.md
- docs/platform/howto/update-tax-status.md
- docs/platform/howto/use-billing-groups.md
> update: add super admin note to billing pages

- docs/products/cassandra/get-started.md
- docs/products/clickhouse/get-started.md
- docs/products/mysql/get-started.md
- docs/products/postgresql/get-started.md
Fixing bugs and implementing some most obvious editorial improvements 
https://aiven.atlassian.net/browse/DOC-809
> update(getting started): fixes of format, lg, and style issues

- .github/vale/styles/config/vocabularies/Aiven/accept.txt
- docs/products/flink/howto/manage-credentials-jars.md
- docs/products/postgresql/howto/monitor-database-with-datadog.md
- docs/tools/cli/service/integration.md
- sidebars.ts
> add(Flink): Flink JAR credentials management

- docs/products/redis/concepts/memory-usage.md
> update: Correct maxmemory setting and eviction policy

- docs/products/dragonfly/howto/eviction-policy-df.md
- sidebars.ts
> add: eviction policy Dragonfly

- docs/products/dragonfly/get-started.md
> update: service integration update to DF get started 

- docs/tools/cli/service/integration.md
> fix: broken link

- docs/platform/concepts/application-users.md
- docs/platform/howto/manage-application-users.md
- sidebars.ts
Adds documentation for the application users feature.
> add: application users docs

- docs/platform/concepts/static-ips.md
https://aiven.atlassian.net/browse/DOC-850
> add(platform): warning on static ip costs

- docs/platform/reference/eol-for-major-versions.md
https://aiven.atlassian.net/browse/DOC-839
> add(postgresql): release 16 EOL dates

- docs/tools/terraform/howto/migrate-from-teams-to-groups.md
- sidebars.ts
Add instructions and samples for migrating from teams to groups using Terraform.
> add: TF instructions to migrate to groups

- docs/platform/concepts/managed-users.md
Make it clearer that managed users are created by verifying a domain.
> update: clarify how managed users work

- docs/platform/reference/eol-for-major-versions.md
https://aiven.atlassian.net/browse/DOC-867
> update(cassandra): eol dates for 4.0 and 4.1 versions

- .vscode/aiven.code-snippets
- docs/platform/concepts/carbon-footprint.md
- sidebars.ts
Add documentation on the new carbon footprint tool.
> add(platform): carbon footprint doc

- docs/platform/concepts/static-ips.md
- docs/platform/howto/pause-from-cli.md
- static/includes/static-ip-cost-warning.md
https://aiven.atlassian.net/browse/DOC-875
> update(platform): add ip cost warning to the service termination doc

- docs/platform/concepts/billing-groups.md
- docs/platform/concepts/hourly-billing-model.md
- docs/platform/concepts/list-billing.md
- docs/platform/howto/list-account.md
- docs/platform/howto/list-billing-groups.md
- docs/platform/howto/list-byoc.md
- sidebars.ts
- static/_redirects
Levering overview pages instead of empty landing pages.
> update: use overview pages as landing pages

- docs/products/dragonfly.md
- docs/products/dragonfly/concepts/ha-dragonfly.md
- docs/products/dragonfly/concepts/overview.md
- docs/products/dragonfly/get-started.md
- docs/products/dragonfly/howto.md
- docs/products/dragonfly/howto/connect-go.md
- docs/products/dragonfly/howto/connect-python.md
- docs/products/dragonfly/howto/list-migrate-data.md
- docs/products/dragonfly/howto/migrate-aiven-redis-df-console.md
- docs/products/dragonfly/howto/migrate-ext-redis-df-console.md
- static/includes/dragonflysla-note.md
Added note to Dragonfly documentation advising customers to run a PoC with Aiven for Dragonfly before full production deployment. Removed LA tags for GA.
[MA-2419](https://aiven.atlassian.net/browse/MA-2419)
[MA-2419]: https://aiven.atlassian.net/browse/MA-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update: Add note about SLA and prepare for GA

- docs/products/clickhouse/get-started.md
https://aiven.atlassian.net/browse/DOC-881
> update(clickhouse): create db update

- docs/platform/howto/vpc-peering-gcp.md
https://aiven.atlassian.net/browse/DOC-912
> update(platform): add multiple vpc peering connections on gcp

- docs/platform/howto/make-super-admin.md
Minor edits to super admin doc title and language.
> update: super admin

- .github/vale/styles/config/vocabularies/Aiven/accept.txt
- docs/products/postgresql/howto/pgbouncer-stats.md
https://aiven.atlassian.net/browse/DOC-942
> update(postgresql): add connect to pgbouncer command

- docs/platform/reference/project-member-privileges.md
Fix project member role descriptions.
> update: project role permissions

- docs/platform/concepts/service-integration.md
- docs/platform/howto/create-service-integration.md
- docs/platform/howto/restrict-access.md
https://aiven.atlassian.net/browse/AD-2258
> update(platform): service integrations and restrict access with ip filter

- docs/platform/howto/okta-user-provisioning-with-scim.md
- docs/platform/howto/saml/add-identity-providers.md
- docs/platform/howto/saml/add-okta-idp.md
- sidebars.ts
Add article on SCIM user provisioning to meet Okta requirements for integration.
> add: user provisioning for Okta with SCIM

- docs/products/dragonfly/concepts/overview.md
Removed duplicate content in the Dragonfly landing page and Dragonfly overview page.
> update: removed duplicate content

- docs/products/postgresql/get-started.md
- docusaurus.config.ts
https://aiven.atlassian.net/browse/DOC-794
> update(postgresql): get-started guide improvements

- docs/products/metrics/concepts/retention-rules.md
- sidebars.ts
Added TOC entry for Retention rules topic
> update: fix toc entry

- docs/platform/howto/vnet-peering-azure.md
https://aiven.atlassian.net/browse/DOC-972
> update(platform): update password info for vpc peering setup on Azure

- docs/platform/concepts/application-users.md
- docs/platform/howto/manage-application-users.md
Remove LA tag from application user docs and apply style guide changes.
> update(platform): remove LA tag for application users

- docs/products/kafka/howto/enable-kafka-tiered-storage.md
https://aiven.atlassian.net/browse/DOC-975
> update(kafka): add more tiered storage prerequisites

- docs/products/mysql/howto/migrate-db-to-aiven-via-console.md
wal_format -> binlog_format
max_replication_slots -> max_connections
There are potentially other issues, such as the note about "logical replication", but this stood out as obviously incorrect for MySQL.
> fix(mysql): Switch PostgreSQL config variables to MySQL

- docs/products/clickhouse/howto/query-databases.md
- docs/products/clickhouse/reference/limitations.md
https://aiven.atlassian.net/browse/DOC-930
https://aiven.atlassian.net/browse/DOC-981
> update(clikchouse): maximum concurrent queries & connections

- docs/platform/howto/byoc/create-custom-cloud.md
https://aiven.atlassian.net/browse/DOC-985
> update(platfrom): add permissions section in the BYOC docs

- docs/platform/concepts/aiven-node-firewall-configuration.md
> add(platform): wireguard port in firewall config

- docs/tools/terraform/howto/migrate-from-teams-to-groups.md
Teams are now GA in Terraform. This removes the step to set the beta env variable.
> update: teams are no longer beta

- docs/products/kafka/karapace/howto/manage-schema-registry-authorization.md
- docs/tools/terraform/get-started.md
- docs/tools/terraform/howto/config-postgresql-provider.md
- docs/tools/terraform/howto/promote-to-master-pg-rr.md
- docs/tools/terraform/howto/upgrade-provider-v1-v2.md
- docs/tools/terraform/howto/upgrade-provider-v2-v3.md
- docs/tools/terraform/howto/upgrade-provider-v3-v4.md
- docs/tools/terraform/howto/use-opentofu.md
Change all TF code blocks to use HCL for syntax highlighting.
> update: TF code blocks to hcl

- docs/platform/howto/saml/add-identity-providers.md
Changes the structure and some wording of the final steps for linking a user account to an IdP for clarity.
> update: linking profiles to IdPs

- docs/products/clickhouse/concepts/clickhouse-tiered-storage.md
- docs/products/clickhouse/howto/enable-tiered-storage.md
https://aiven.atlassian.net/browse/DOC-992
> update(clickhouse): add clouds supporting tiered storage

- docs/products/postgresql/howto/pgbouncer-stats.md
https://aiven.atlassian.net/browse/DOC-1013
> update(postgresql): pgbouncer stats improvements

- docs/platform/reference/eol-for-major-versions.md
Add Flink service end of life dates.
> add: flink dates

- docs/platform/howto/byoc/add-customer-info-custom-cloud.md
- docs/platform/howto/byoc/assign-project-custom-cloud.md
- docs/platform/howto/byoc/create-custom-cloud.md
- docs/platform/howto/byoc/delete-custom-cloud.md
- docs/platform/howto/byoc/enable-byoc.md
- docs/platform/howto/byoc/rename-custom-cloud.md
- src/components/ConsoleIcons/index.tsx
https://aiven.atlassian.net/browse/DOC-1025
> add(platform): console icon for byoc

- docs/tools/cli/byoc.md
- sidebars.ts
https://aiven.atlassian.net/browse/MILK-115
> add(platform): byoc avn client commands

- docs/products/postgresql/howto/manage-extensions.md
I updated the [documentation](https://aiven.io/docs/products/postgresql/howto/manage-extensions#request-a-new-extension) that stated how to request a new extension, to be more accurate. The customer should do this through the Ideas Portal, not create a support ticket, since we just divert them to that anyway
JIRA ticket
https://aiven.atlassian.net/browse/SRE-8655
> update: the 'request a new extension' section

- docs/platform/howto/disk-autoscaler.md
- docs/platform/howto/scale-services.md
https://aiven.atlassian.net/browse/AD-2180
> update(platform): service disk autoscaler GA

- docs/platform/concepts/application-users.md
- docs/platform/howto/make-super-admin.md
- docs/platform/howto/manage-application-users.md
- src/components/ConsoleIcons/index.tsx
Instructions for making application users super admin and related updates.
> add(platform): make application users super admin

- docs/platform/howto/saml/add-okta-idp.md
> update: clarify attribute statements for Okta

- docs/platform/howto/add-storage-space.md
- docs/platform/howto/disk-autoscaler.md
- Harmonize SEO for similar pages
- Harmonize sections
- Small content optimizations
> update: harmonize terminology to improve SEO

- docs/products/opensearch/concepts/cross-cluster-replication-opensearch.md
- docs/products/opensearch/howto/setup-cross-cluster-replication-opensearch.md
The request was to remove HA and DR content from the concept for now. 
Removed the following points: 
- High availability and Disaster recovery (active-passive): With tolerance for outages or complete failure of clusters, cross-cluster replication ensures uninterrupted service availability with the ability to failover to an alternate cluster.
- Centralized reporting cluster: Having a single replica cluster as a single source of truth between different master cluster
> update: concept for OS CCR

- docs/platform/howto/saml/add-identity-providers.md
- docs/platform/howto/saml/add-okta-idp.md
> update: okta instructions

- docs/platform/howto/saml/add-okta-idp.md
> update: remove relay state troubleshooting

- docs/platform/howto/use-azure-privatelink.md
https://aiven.atlassian.net/browse/MILK-153
> fix(platform): azure privatelink comand fix

- docs/products/clickhouse/howto/manage-users-roles.md
https://aiven.atlassian.net/browse/DDB-1045
> update(clickhouse): more clarity for users and roles

- docs/platform/howto/byoc/download-infrastructure-template.md
- sidebars.ts
https://aiven.atlassian.net/browse/MILK-155
> add(platform): download a BYOC infra template

- docs/platform/howto/saml/add-okta-idp.md
- Adds instructions for configuring relay state
- Adds troubleshooting for invalid relay state errors
> update: Okta steps

- docs/platform/concepts/orgs-units-projects.md
Improving the the user roles section and adding in the service-level users.
> update: user roles and permissions

- docs/platform/concepts/disaster-recovery-test-scenarios.md
- docs/platform/howto/support.md
Update the contact details for services available on higher level support tiers.
> update: contact for services

- docs/products/postgresql/reference/pg-connection-limits.md
Following up on https://github.com/aiven/aiven-docs/pull/267
> update(postgresql): pg max connection note

- docs/products/clickhouse/reference/supported-input-output-formats.md
https://aiven.atlassian.net/browse/DDB-1065
> add(clickhouse): parquet format for clickhouse kafka data exchange

- docs/products/clickhouse/concepts/clickhouse-tiered-storage.md
- docs/products/clickhouse/howto/list-tiered-storage.md
- docs/products/clickhouse/howto/transfer-data-tiered-storage.md
https://aiven.atlassian.net/browse/DDB-1037
> update(clickhouse): tiered storage tweaks

- docs/platform/howto/okta-user-provisioning-with-scim.md
Add password sync as a supported feature for SCIM.
> update(platform): sync password feature for SCIM

- docs/products/postgresql/reference/list-of-extensions.md
https://aiven.atlassian.net/browse/BF-2607
> add(postgresql): h3pg extension

- docs/products/postgresql/reference/list-of-extensions.md
> update(postgresql): h3 extension

- docs/platform/howto/use-google-private-service-connect.md
https://aiven.atlassian.net/browse/MILK-182
> update(platform): Google PSC not supported for PostgreSQL

- docs/tools/aiven-console/howto/create-manage-teams.md
Makes the differences between super admin access with teams and groups a bit clearer to address customer feedback.
> update: clarify account owners team changes

- docs/platform/howto/saml/add-identity-providers.md
Dropdown menu option has been changed from SAML to OTHER.
> fix: IdP instructions

- docs/platform/howto/byoc/create-custom-cloud.md
> fix(platform): support tier fix for BYOC

- docs/platform/howto/byoc/networking-security.md
- sidebars.ts
https://aiven.atlassian.net/browse/MILK-185
> add(platform): BYOC networking and security

- docs/products/kafka/karapace/howto/enable-schema-registry-authorization.md
Clarify that the feature cannot be toggled on or off if it's by default on per the discussion [here](https://aiven-io.slack.com/archives/C071699P2R2/p1720102957881719).
> update: Update enable-schema-registry-authorization.md

- docs/products/mysql/howto/connect-with-java.md
I've changed the command for checking the connection since _mysql-connector-java-8.0.28.jar:._ didn't work for me but _"mysql-connector-java-8.0.28.jar;."_ did.
Tested on Windows 11 (MobaXterm Personal Edition v24.2, Apache NetBeans IDE 20)
> update(mysql): connect-with-java.md 

- docs/platform/concepts/cloud-security.md
> update(platform): Remove reference to support for SBOM

- docs/products/cassandra/get-started.md
- docs/products/cassandra/overview.md
- docs/products/clickhouse/howto/list-get-started.md
- docs/products/clickhouse/list-overview.md
- docs/products/mysql/overview.md
- docs/products/postgresql/howto/pagila.md
- docs/products/postgresql/overview.md
- sidebars.ts
- static/_redirects
https://aiven.atlassian.net/browse/DOC-1102
> update(clickhouse): remove duplicated content

- docs/platform/howto/okta-user-provisioning-with-scim.md
- docs/platform/howto/saml/add-identity-providers.md
Remove LA flag for SCIM for the GA release.
> update(platform): remove LA flag for SCIM

- docs/products/metrics/howto/list-data-migration.md
- sidebars.ts
Added a new landing page for data migration to Aiven for Metrics, which will be linked to the banner on the service overview page.
ref: https://www.figma.com/design/rwmHzjF2btpoqoDuPCTlzr/Thanos?node-id=3973-22975&t=L22KGUBbjujtixga-0
> add: Data migration landing page

- docs/platform/howto/saml/add-identity-providers.md
Updates instructions to reflect changes in the wizard.
> update: IdP instructions for UI changes

- docs/products/kafka/kafka-connect/get-started.md
- docs/products/kafka/kafka-mirrormaker/get-started.md
- docs/products/opensearch/dashboards/get-started.md
- docs/tools/api.md
- docs/tools/cli.md
Improve H1/H2 specificity to fix unclear search hits.
> update(seo): increase get started specificity

- docs/platform/reference/eol-for-major-versions.md
https://aiven.atlassian.net/browse/DDB-1164
> update(cassandra): cassandra 4.0 service creation support date

- docs/products/kafka/howto/approvals.md
- docs/products/kafka/howto/claim-topic.md
- docs/products/kafka/howto/group-requests.md
- docs/products/kafka/howto/manage-resource-requests.md
- package.json
- sidebars.ts
- src/components/ConsoleIcons/index.tsx
- yarn.lock
Added content for topic claim, approval, and group request workflow.
> add: Topic claim, approval and group request workflows

- docs/platform/howto/use-azure-privatelink.md
https://aiven.atlassian.net/browse/MILK-241
> update(platform): azure private link early availability

- docs/products/postgresql/howto/setup-logical-replication.md
https://aiven.atlassian.net/browse/DOC-1113
> fix(postgresql): add a missing argument to the stop logical replication command

- docs/products/kafka/concepts/topic-catalog-overview.md
- docs/products/kafka/howto/manage-topics-details.md
- docs/products/kafka/howto/use-kafka-topic-catalog.md
- docs/products/kafka/howto/view-kafka-topic-catalog.md
- sidebars.ts
Concept and how-to topics for the topic catalog
> add: Apache Kafka topic catalog

- docs/products/kafka/concepts/governance-overview.md
- docs/products/kafka/howto/approvals.md
- docs/products/kafka/howto/claim-topic.md
- docs/products/kafka/howto/enable-governance.md
- docs/products/kafka/howto/governance.md
- docs/products/kafka/howto/group-requests.md
- docs/products/kafka/howto/manage-resource-requests.md
- docs/products/kafka/howto/view-kafka-topic-catalog.md
- package.json
- sidebars.ts
- src/components/ConsoleIcons/index.tsx
- yarn.lock
- Governance overview 
- Enabling governance for the organization
> add: Governance overview and enabling content

- docs/platform/howto/use-azure-privatelink.md
https://aiven.atlassian.net/browse/MILK-244
> update(platform): azure private link contact for enablement removal

- docs/products/kafka/howto/enable-follower-fetching.md
- src/components/ConsoleIcons/index.tsx
Steps on how to enable follower fetching via API and Terraform
> add: Enable follower fetching via API

- docs/platform/concepts/service_backups.md
- docs/products/cassandra/get-started.md
https://aiven.atlassian.net/browse/DOC-796
> update(cassandra): getting started

- docs/products/kafka/howto/approvals.md
- package.json
- src/components/ConsoleIcons/index.tsx
- yarn.lock
Fixed missing icons and added a new award icon.
> fix: missing icons for governance

- sidebars.ts
- src/components/HomepageFeatures/index.tsx
- static/images/icons/home/cloud.svg
https://aiven.atlassian.net/browse/DOC-1127
> update(BYOC): promote byoc docs in the doc set

- docs/products/kafka/concepts/follower-fetching.md
- docs/products/kafka/howto/enable-follower-fetching.md
ref: https://aiven.atlassian.net/browse/HH-4231
> update: follower fetching content updated to include GCP

- docs/platform/concepts/free-plan.md
Add AWS hosting to free plans.
> update: add AWS to free plan hosting

- docs/platform/howto/manage-vpc-peering.md
> add: Add network range limitation note for creating new a VPC

- docs/products/valkey.md
- docs/products/valkey/get-started.md
- docs/products/valkey/howto/connect-go.md
- docs/products/valkey/howto/connect-java.md
- docs/products/valkey/howto/connect-node.md
- docs/products/valkey/howto/connect-php.md
- docs/products/valkey/howto/connect-python.md
- docs/products/valkey/howto/connect-services.md
- docs/products/valkey/reference/advanced-params.md
- sidebars.ts
Added trademark ™ to Valkey and Aiven for Valkey.
[DOC-1154](https://aiven.atlassian.net/browse/DOC-1154)
[DOC-1154]: https://aiven.atlassian.net/browse/DOC-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: trademark for Aiven for Valkey

- docs/products/clickhouse/howto/create-dictionary.md
https://aiven.atlassian.net/browse/DDB-1150
> update: clickhouse dictionaries now named collections is released

- docs/platform/howto/byoc/create-custom-cloud.md
- src/components/ConsoleIcons/index.tsx
https://aiven.atlassian.net/browse/MILK-272
> update(BYOC): add variables definitions for BYOC GC instructions

- docusaurus.config.ts
- package.json
- yarn.lock
Enable click on images to see them full size.
> add: image zoom

- docs/products/opensearch/howto/migrate-external-snapshots-aiven-opensearch.md
- docs/products/opensearch/howto/migrate-opendistro-security-config-aiven.md
- docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
- docs/products/opensearch/howto/restore-snapshot-opensearch.md
- sidebars.ts
Documentation for snapshot restoration in Aiven for OpenSearch. 
Ref: [MA-2784](https://aiven.atlassian.net/browse/MA-2784)
Preview: 
- https://harshini-os-snapshot-restora.aiven-docs.pages.dev/docs/products/opensearch/howto/migrate-external-snapshots-aiven-opensearch
- https://harshini-os-snapshot-restora.aiven-docs.pages.dev/docs/products/opensearch/howto/restore-snapshot-opensearch
[MA-2784]: https://aiven.atlassian.net/browse/MA-2784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: OpenSearch snapshot restoration

- docs/platform/howto/change-your-email-address.md
Adds optional step to make a user a super admin to keep the permissions the same for the new email address.
> update: change email instructions

- docs/platform/concepts/orgs-units-projects.md
- docs/platform/howto/add-groups-projects.md
- docs/platform/howto/add-project-members.md
- docs/platform/howto/manage-project.md
- docs/platform/reference/project-member-privileges.md
- docs/products/kafka/howto/enable-governance.md
- docs/products/kafka/howto/view-kafka-topic-catalog.md
- docs/tools/aiven-console.md
- src/components/ConsoleIcons/index.tsx
Changes references to the UI label members for projects to the new label, permissions.
> update: project members to permissions

- docs/platform/howto/add-storage-space.md
https://aiven.atlassian.net/browse/AD-2709
> update(platform): performance degradation after adding disk storage

- docs/get-started.md
Adds categories of first steps.
> update: get started first steps

- docs/platform/howto/manage-vpc-peering.md
- docs/platform/howto/restrict-access.md
https://aiven.atlassian.net/browse/MILK-276
> update(platform): ip filter

- docs/products/caching/howto/manage-ssl-connectivity.md
- yarn.lock
Updated documentation to reflect changes in HAProxy timeout settings.
Ref: [DOC-1182](https://aiven.atlassian.net/browse/DOC-1182) and [MA-2632](https://aiven.atlassian.net/browse/MA-2632)
[DOC-1182]: https://aiven.atlassian.net/browse/DOC-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MA-2632]: https://aiven.atlassian.net/browse/MA-2632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update: caching haproxy timeout

- docs/products/opensearch/howto/migrate-ism-policies.md
- docs/products/opensearch/howto/migrate-opendistro-security-config-aiven.md
- docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
Updated OS snapshot migration documentation based on feedback.
- Included corrections to API endpoints and CLI commands and additional clarity on the reapplication of ISM policy.
- Included other feedback based on emulating a customer setup
> update: OS snapshot migration feedback

- docs/products/services.md
> update(alloydb-omni): service component reordered

- docs/platform/howto/use-google-private-service-connect.md
https://aiven.atlassian.net/browse/DOC-1187
> update(privatelink): change to early availability for Google PSC

- docs/products/metrics.md
- docs/products/metrics/get-started.md
- docusaurus.config.ts
- Aiven for Metrics documentation in preparation for General Availability
- Adding information about the current unavailability on Azure and Google Cloud Marketplace. [MA-3001](https://aiven.atlassian.net/browse/MA-3001)
[MA-3001]: https://aiven.atlassian.net/browse/MA-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update: Metrics content for GA

- docs/products/valkey/concepts/read-replica.md
- docs/products/valkey/howto/create-valkey-read-replica.md
- sidebars.ts
Added content for Aiven for Valkey read replica (EA) 
[MA-3014](https://aiven.atlassian.net/browse/MA-3014)
[MA-3014]: https://aiven.atlassian.net/browse/MA-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: Read replica for Aiven for Valkey

- docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
Adding steps in the prerequisite to conduct data migration for OpenSearch
> update: OpenSearch data migration prerequisite 

- docs/products/opensearch/concepts/index-replication.md
Updated replication factor 0 usage guidelines to emphasize caution and align with feedback.
> fix: Refined OS replication factor 0 documentation

- docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
Addressed feedback on snapshot data migration content based on testing
> update: OS snaptshot data migration feedback

- docs/products/opensearch/howto/migrate-ism-policies.md
- docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md
Include changes related to [MA-3058](https://aiven.atlassian.net/browse/MA-3058) and feedback from the team's testing the migration process. 
[MA-2784](https://aiven.atlassian.net/browse/MA-2784)
[MA-3058]: https://aiven.atlassian.net/browse/MA-3058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MA-2784]: https://aiven.atlassian.net/browse/MA-2784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update: Snapshot migration updates

- docs/tools/cli/service/alloydbomni.md
- sidebars.ts
https://aiven.atlassian.net/browse/BF-2907
> add(alloydbomni): avn client commands

- docs/products/clickhouse/concepts/disaster-recovery.md
- docs/products/clickhouse/howto/restore-backup.md
- sidebars.ts
https://aiven.atlassian.net/browse/DDB-1125
> add(clickhouse): restore from a backup

- docs/products/alloydbomni.md
https://aiven.atlassian.net/browse/BF-2906
> add(alloydbomni): info on compatibility with postgresql

- docs/products/clickhouse/howto/check-data-tiered-storage.md
- docs/products/clickhouse/howto/enable-tiered-storage.md
- docs/products/clickhouse/howto/integration-databases.md
- docs/products/clickhouse/howto/list-tiered-storage.md
- docs/products/clickhouse/howto/load-dataset.md
- docs/products/clickhouse/howto/manage-databases-tables.md
- src/components/ConsoleIcons/index.tsx
https://aiven.atlassian.net/browse/DDB-1336
- Aligning with the new **Database and Tables** view in the Aiven Console
- A few other GUI-related fixes in the same docs
> update(clickhouse): databases and tables updates to align with console changes

- docs/get-started.md
- docs/platform/concepts/orgs-units-projects.md
- docs/platform/concepts/permissions.md
- docs/platform/concepts/user-access-management.md
- docs/tools/aiven-console/howto/create-manage-teams.md
- docs/tools/terraform/howto/migrate-from-teams-to-groups.md
Update overview information about orgs and units centralizing role and permission details on the one page. Update links to this page.
> update: user and roles references

- docs/products/caching/howto/upgrade-aiven-for-caching-to-valkey.md
- docs/tools/terraform/howto/upgrade-caching-valkey-terraform.md
- sidebars.ts
Upgrade from Aiven for Caching to Aiven for Valkey™ as part of Aiven Caching EOL. 
[MA-2801](https://aiven.atlassian.net/browse/MA-2801)
[MA-2961](https://aiven.atlassian.net/browse/MA-2961)
[MA-2801]: https://aiven.atlassian.net/browse/MA-2801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MA-2961]: https://aiven.atlassian.net/browse/MA-2961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: Upgrade Caching to Valkey

- docs/products/postgresql/reference/list-of-extensions.md
https://aiven.atlassian.net/browse/BF-2914
> update(postgresql): remove the superuser extensions list

- docs/platform/howto/restrict-access.md
Change "Public IP filters" to the new Console label "IP address allowlist".
> update: IP filters label

- docs/platform/howto/byoc/tag-custom-cloud-resources.md
- docs/tools/cli/byoc.md
https://aiven.atlassian.net/browse/MILK-359
> update(BYOC): add byoc tag aiven client commands

- docs/platform/howto/saml/add-auth0-idp.md
- docs/platform/howto/saml/add-azure-idp.md
- docs/platform/howto/saml/add-google-idp.md
- docs/platform/howto/saml/add-identity-providers.md
- docs/platform/howto/saml/add-jumpcloud-idp.md
- static/includes/idp-step3.md
Add information about SAML group syncing.
> update: add SAML group syncing to IdP instructions

- docs/products/clickhouse/howto/manage-databases-tables.md
- docs/products/clickhouse/howto/query-databases.md
https://aiven.atlassian.net/browse/DDB-1357
> add(clickhouse): how to query a query log

- docs/platform/concepts/tls-ssl-certificates.md
- docs/products/postgresql/howto/list-code-samples.md
https://aiven.atlassian.net/browse/DOC-1214
> update(postgresql): update SSL & certificate info

- docs/products/metrics/concepts/storage-resource-scaling.md
- docs/products/metrics/howto/download-influxdb-data.md
- docs/products/metrics/howto/storage-usage.md
- sidebars.ts
Add content on how to download Aiven for InfluxDB data using Console, API, and CLI. It also includes restructuring/ordering of content. 
[MA-3097](https://aiven.atlassian.net/browse/MA-3097)
Preview - https://harshini-download-influxdb-d.aiven-docs.pages.dev/docs/products/metrics/howto/download-influxdb-data
[MA-3097]: https://aiven.atlassian.net/browse/MA-3097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: Content on how to download influxDB data

- docs/products/postgresql/howto/upgrade.md
https://aiven.atlassian.net/browse/BF-2939
> update(postgresql): upgrade best practices

- docs/products/clickhouse/reference/limitations.md
- docs/products/clickhouse/reference/plans-pricing.md
- static/includes/clickhouse-storage-limitation.md
https://aiven.atlassian.net/browse/DDB-1361
> add(clickhouse): total storage limitation

- docs/products/clickhouse/concepts/data-integration-overview.md
https://aiven.atlassian.net/browse/DDB-1359
> update(clickhouse): integration data flow and residency

- docs/products/kafka/kafka-mirrormaker/concepts/mirrormaker2-tuning.md
- docs/products/kafka/kafka-mirrormaker/howto/monitor-replication-execution.md
- sidebars.ts
Explained the different configuration layers and moved monitoring instructions to howto section.
[DOC-1169]
[DOC-1169]: https://aiven.atlassian.net/browse/DOC-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update(MirrorMaker): improve configuration concepts

- .github/workflow-config/labeling-rules.yaml
Harmonize labels with user config parameter values.
> update: harmonize label names

- .vscode/aiven.code-snippets
- docs/get-started.md
- docs/platform/concepts/application-users.md
- docs/platform/concepts/billing-and-payment.md
- docs/platform/concepts/billing-groups-overview.md
- docs/platform/concepts/carbon-footprint.md
- docs/platform/concepts/managed-users.md
- docs/platform/concepts/tax-information.md
- docs/platform/concepts/user-access-management.md
- docs/platform/howto/billing-assign-projects.md
- docs/platform/howto/byoc/add-customer-info-custom-cloud.md
- docs/platform/howto/byoc/assign-project-custom-cloud.md
- docs/platform/howto/byoc/create-custom-cloud.md
- docs/platform/howto/byoc/delete-custom-cloud.md
- docs/platform/howto/byoc/download-infrastructure-template.md
- docs/platform/howto/byoc/enable-byoc.md
- docs/platform/howto/byoc/rename-custom-cloud.md
- docs/platform/howto/byoc/tag-custom-cloud-resources.md
- docs/platform/howto/change-your-email-address.md
- docs/platform/howto/download-invoices.md
- docs/platform/howto/manage-application-users.md
- docs/platform/howto/manage-payment-card.md
- docs/platform/howto/manage-project.md
- docs/platform/howto/support.md
- docs/platform/howto/use-billing-groups.md
- docs/platform/reference/get-resource-IDs.md
- docs/products/kafka/howto/enable-governance.md
> update: change super admin to org admin

- docs/platform/concepts/free-plan.md
> update: remove cloud provider from free plan

- docs/products/clickhouse/reference/clickhouse-system-tables.md
- sidebars.ts
https://aiven.atlassian.net/browse/DDB-1569
> add(clickhouse): system tables

- docs/products/kafka/kafka-connect/howto/debezium-source-connector-pg.md
> add: Debezium 2.5 config

- docs/platform/howto/make-super-admin.md
> update: add note to super admin doc

- docs/tools/aiven-console/howto/create-orgs-and-units.md
> update: info on impact of creating new orgs

- docs/platform/concepts/permissions.md
> update: add note about projects endpoint to permissions

- docs/products/clickhouse/howto/manage-databases-tables.md
- docs/products/clickhouse/reference/limitations.md
https://aiven.atlassian.net/browse/DDB-1345
> update(clickhouse): create db via sql

- docs/platform/howto/list-identity-providers.md
> update: security best practices for IdPs

- docs/products/kafka/kafka-connect/howto/manage-connector-versions.md
Fixed instructions based on proof testing.
> update: pin connector version

- docs/platform/howto/support.md
> update: clarify instructions for upgrading support tier

- .github/vale/styles/config/vocabularies/Aiven/accept.txt
- docs/platform/howto/saml/add-azure-idp.md
> update: UI label for entity ID in Azure

- src/components/non-swizzled/Card/styles.module.css
- src/css/custom.css
- src/theme/DocCard/index.tsx
- src/theme/DocCard/styles.module.css
Harmonize the styling of our 2 card components and improve line height.
> style: harmonize card styling

- docs/platform/reference/end-of-life.md
https://aiven.atlassian.net/browse/DDB-1610
> update: Cassandra EoL and deprecation info

- docs/platform/concepts/service_backups.md
- static/includes/edit-backup-schedule.md
https://aiven.atlassian.net/browse/DDB-1556
> update: Valkey & Dragonfly backup info

- docs/products/postgresql/howto/pagila.md
https://aiven.atlassian.net/browse/DOC-1321
> update: Pagila sample dataset for PG

- docs/products/postgresql/howto/report-metrics-grafana.md
https://aiven.atlassian.net/browse/DOC-1330
> update: replace m3bd with aiven for metrics

- docs/platform/concepts/authentication-tokens.md
> update: tokens overview

- docs/platform/reference/change-password.md
- sidebars.ts
> feat: instructions for changing passwords

- docs/platform/howto/use-aws-privatelinks.md
- docs/platform/howto/use-azure-privatelink.md
- docs/platform/howto/use-google-private-service-connect.md
https://aiven.atlassian.net/browse/MILK-445
> update: private link not supported for BYOC

- docs/products/kafka/concepts/upgrade-procedure.md
Add KRaft details to the Kafka upgrade procedure documentation
Preview - https://harshini-kraft-updates.aiven-docs.pages.dev/docs/products/kafka/concepts/upgrade-procedure#transitioning-to-kraft-
[HH-5036](https://aiven.atlassian.net/browse/HH-5036)
[HH-5036]: https://aiven.atlassian.net/browse/HH-5036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: KRaft details to Kafka upgrade procedure

- docs/tools/aiven-console/howto/create-orgs-and-units.md
Removes the step for assigning projects as this has been removed from the UI. Fixes some typos and aligns some text with the style guide.
> update: instrutions for creating organizational units

- .github/workflows/redirection-reminder.yaml
Remind contributors to add redirections.
> ci: check missing redirects

- docs/products/clickhouse/reference/clickhouse-system-tables.md
- docs/products/clickhouse/reference/supported-table-functions.md
https://aiven.atlassian.net/browse/DDB-1733
> update: ClickHouse 24.8 table functions and engines

- docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md
Improvements to the Iceberg sink connector docs based on feedback. 
Preview - https://kcon-112-update-docs-based-o.aiven-docs.pages.dev/docs/products/kafka/kafka-connect/howto/iceberg-sink-connector
[KCON-112](https://aiven.atlassian.net/browse/KCON-112)
[KCON-112]: https://aiven.atlassian.net/browse/KCON-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update: improvements to Iceberg sink connector

- docs/products/kafka/kafka-connect/howto/manage-connector-versions.md
- src/components/non-swizzled/ConsoleIcons/index.tsx
https://aiven.atlassian.net/browse/EC-724
> update: Aiven console steps for multi-version connectors

- docs/products/kafka/kafka-connect/howto/clickhouse-sink-connector.md
- docs/products/kafka/kafka-mirrormaker/howto/exactly-once-delivery.md
- src/components/ConsoleIcons/index.tsx
https://aiven.atlassian.net/browse/DOC-1353
> fix: missing icons

- static/includes/clouds-list.md
https://aiven.atlassian.net/browse/AD-3095
> update: List of cloud - OCI ca-montreal-1 region

- .dockerignore
- .github/workflow-config/labeling-rules.yaml
- Dockerfile
- README.md
- docker-compose.yml
- package.json
- yarn.lock
Add Docker way to build the docs.
> ci: add Docker file

- docs/products/clickhouse/reference/limitations.md
https://aiven.atlassian.net/browse/DDB-1809
> update: clickhouse startup 32 and 64 plans

- static/includes/clouds-list.md
https://aiven.atlassian.net/browse/AD-3066
> feat: Google Cloud south-africa-1 region

- docs/products/postgresql/concepts/upgrade-failover.md
https://aiven.atlassian.net/browse/BF-3193
> update: pg replication slots update

- static/includes/clouds-list.md
https://aiven.atlassian.net/browse/AD-3069
> feat: Google Cloud northamerica-south1 region

- docs/products/kafka/howto/request-access-topic.md
- sidebars.ts
- src/components/ConsoleIcons/index.tsx
Request access to read or write to kafka topic in governance
> feat: Request access to read or write to kafka topic in governance

- docs/platform/howto/byoc/delete-custom-cloud.md
- docs/platform/howto/manage-organization-vpc.md
- docs/platform/howto/manage-project-vpc.md
- docs/products/kafka/howto/manage-acls.md
- static/includes/vpc/delete-org-peering.md
- static/includes/vpc/delete-pj-peering.md
> fix: instructions to remove Terraform resources

- docs/products/opensearch/howto/custom-repositories.md
- sidebars.ts
Added documentation on creating custom repositories for OpenSearch snapshots.
[MA-3270](https://aiven.atlassian.net/browse/MA-3270)
[MA-3270]: https://aiven.atlassian.net/browse/MA-3270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add support for custom repositories in OpenSearch snapshots

- .github/workflows/update-terraform-submodule.yaml
- .gitmodules
- .vscode/aiven.code-snippets
- docs/tools/aiven-console/howto/create-orgs-and-units.md
- src/components/CodeSamples/TerraformSample/index.tsx
> feat: sync Terraform code samples

- docs/products/clickhouse/concepts/disaster-recovery.md
- docs/products/clickhouse/howto/configure-backup.md
- docs/products/clickhouse/howto/restore-backup.md
- sidebars.ts
https://aiven.atlassian.net/browse/DDB-1588
> feat: configure ClickHouse backup time

- docs/platform/concepts/application-users.md
- docs/platform/howto/manage-application-users.md
- docs/platform/howto/manage-groups.md
- docs/platform/howto/manage-permissions.md
- docs/platform/howto/manage-project.md
- docs/platform/howto/technical-emails.md
- docs/tools/aiven-console/howto/create-orgs-and-units.md
Embeds Terraform example usage and links to relevant resources for orgs, projects, groups, application users, technical emails, and permissions.
> update: add Terraform example usage to platform features

- .github/workflows/create-index-algolia.yaml
- .github/workflows/delete-unused-images.yaml
- .github/workflows/link-checker.yaml
- .github/workflows/redirection-reminder.yaml
- .github/workflows/update-adv-params.yaml
- .github/workflows/update-cloud-list.yaml
> fix: fetch submodules during checkouts in workflows

- .vscode/aiven.code-snippets
- docs/platform/concepts/maintenance-window.md
- docs/platform/concepts/service_backups.md
- docs/platform/howto/add-storage-space.md
- docs/platform/howto/byoc/tag-custom-cloud-resources.md
- docs/platform/howto/create_new_service_user.md
- docs/platform/howto/migrate-services-cloud-region.md
- docs/platform/howto/scale-services.md
- docs/platform/howto/tag-resources.md
- docs/tools/aiven-console/howto/create-orgs-and-units.md
Adds Terraform instructions for creating service users, tagging resources, adding storage space, migrating services, scaling services, configuring maintenance and backups.
> update: add Terraform instructions

- docs/platform/howto/tag-resources.md
> update: tag limits

- static/includes/clouds-list.md
https://aiven.atlassian.net/browse/AD-3142
> update: list of clouds: google-europe-north-2 region

- docs/products/clickhouse/howto/integration-databases.md
- docs/products/clickhouse/howto/manage-databases-tables.md
- docs/products/clickhouse/reference/limitations.md
https://aiven.atlassian.net/browse/DDB-1834
> update: max number of ClickHouse DBs

- .github/vale/styles/config/vocabularies/Aiven/accept.txt
- docs/products/kafka/howto/approvals.md
- docs/products/kafka/howto/terraform-governance-approvals.md
- sidebars.ts
Governance topic approval via Terraform and GitHub Actions
Preview - https://gov-411-documentation-terraf.aiven-docs.pages.dev/docs/products/kafka/howto/terraform-governance-approvals
[GOV-411](https://aiven.atlassian.net/browse/GOV-411)
[GOV-411]: https://aiven.atlassian.net/browse/GOV-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Governance topic approval via Terraform and GitHub Actions

- docs/products/postgresql/howto/repair-pg-index.md
- docs/products/postgresql/troubleshooting/troubleshooting-connection-pooling.md
- docs/products/postgresql/troubleshooting/troubleshooting-fatal-out-of-shared-mem.md
- sidebars.ts
help article for out of shared memory alert of pg
> update: add user doc for out of shared memory alert

- docs/platform/howto/delete-user.md
- docs/platform/howto/manage-organizations.md
- src/components/ConsoleIcons/index.tsx
> update: instructions for leaving orgs and deleting user accounts

- docs/products/clickhouse/reference/limitations.md
- sidebars.ts
https://aiven.atlassian.net/browse/DDB-1851
> update: clickhouse startup plan cpu

- docusaurus.config.ts
> update: new tagline

- docs/products/kafka/howto/enable-follower-fetching.md
- docs/products/kafka/howto/manage-acls.md
- docs/products/kafka/kafka-connect/howto/manage-connector-versions.md
- docs/products/kafka/kafka-mirrormaker/howto/exactly-once-delivery.md
- docs/products/kafka/karapace/howto/manage-schema-registry-authorization.md
- docs/products/opensearch/howto/setup-cross-cluster-replication-opensearch.md
> update: replace TF code samples with synced samples

- docs/platform/concepts/free-plan.md
- docs/platform/howto/support.md
- docusaurus.config.ts
> update: remove links to Aiven Community forum

- docs/platform/howto/disk-autoscaler.md
> update: add links to TF examples for autoscaler

- docs/products/clickhouse/howto/data-service-integration.md
- docs/products/clickhouse/howto/integrate-kafka.md
- docs/products/clickhouse/howto/integration-databases.md
- docs/products/clickhouse/reference/limitations.md
https://aiven.atlassian.net/browse/DDB-1854
> update: clickhouse - kafka integration improvements

- docs/platform/howto/create-service-integration.md
- docs/products/metrics/get-started.md
> update: terraform for thanos get started and creating integrations

- docs/platform/howto/manage-project.md
> update: info on moving projects

- docs/products/kafka/howto/request-access-topic.md
Terraform flow for Request access.  Depends on - https://github.com/aiven/terraform-provider-aiven/pull/2072
[GOV-645](https://aiven.atlassian.net/browse/GOV-645)
[GOV-645]: https://aiven.atlassian.net/browse/GOV-645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Request access for topics via Terraform

- docs/platform/howto/manage-organization-vpc.md
- docs/platform/howto/manage-project-vpc.md
- docs/platform/howto/vpc-service-management.md
- sidebars.ts
https://aiven.atlassian.net/browse/MILK-478
> update: migrate a service in a VPC to another cloud

- docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md
- docs/products/kafka/kafka-connect/howto/jdbc-catalog-postgres.md
- sidebars.ts
Content for PostgreSQL JDBC catalog for Iceberg sink connector
[KCON-117 ](https://aiven.atlassian.net/browse/KCON-117)
> feat: JDBC catalog for Iceberg sink connector

- docs/products/kafka/howto/snowflake-open-catalog.md
- docs/products/kafka/kafka-connect/howto/aws-glue-catalog.md
- docs/products/kafka/kafka-connect/howto/aws-glue-rest-catalog.md
- docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md
- sidebars.ts
Add documentation for configuring the Iceberg sink connector with Snowflake Open Catalog (Polaris)
[KCON-127](https://aiven.atlassian.net/browse/KCON-127)
[KCON-127]: https://aiven.atlassian.net/browse/KCON-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Snowflake Open Catalog for Iceberg sink connector

- docs/products/alloydbomni/reference/list-of-extensions.md
https://aiven.atlassian.net/browse/BF-3286
> update: alloydb unsupported extensions

- docs/platform/concepts/free-plan.md
> update: free plan limitations

- docs/platform/howto/use-google-private-service-connect.md
https://aiven.atlassian.net/browse/MILK-471 + editorial fixes
> feat: Google Private Service Connect enabled for PG

- docs/platform/concepts/billing-and-payment.md
- docs/platform/howto/trial-credits.md
- sidebars.ts
> update: redeeming trial credits

- docs/platform/howto/manage-project.md
- docs/platform/howto/use-billing-groups.md
> update: clarify limitations of project billing

- docs/products/kafka/kafka-connect/howto/manage-connector-versions.md
Add clarity about potential risks and recommendations related to a connector version switch.
[KCON-251]
[KCON-251]: https://aiven.atlassian.net/browse/KCON-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update: connector mv support

- docs/products/kafka/howto/connect-with-java.md
Examples for connecting to Aiven for Apache Kafka using Java with Karapace (Schema Registry). 
https://aiven.atlassian.net/browse/DOC-1421
> update: Add Java producer and consumer examples for Karapace

- docs/tools/aiven-console/howto/create-orgs-and-units.md
> update: creating organizations with SAML

- docs/platform/howto/manage-domains.md
> update: advise users to keep verification file for domains

- docs/platform/howto/scale-services.md
https://aiven.atlassian.net/browse/IP-406
> update: changing a service plan causes node recycle

- static/includes/clouds-list.md
https://aiven.atlassian.net/browse/AD-3015
> feat: New cloud provider Exoscale (LA)

- docs/products/opensearch/concepts/access_control.md
[PREVIEW
](https://ma-2932-clarify-documentatio.aiven-docs.pages.dev/docs/products/opensearch/concepts/access_control)
https://aiven.atlassian.net/browse/MA-2932
> update: restrict the use of avnadmin by all opensearch roles

- docs/products/opensearch/reference/plugins.md
[PREVIEW](https://ma-3350-remove-ml-commons-an.aiven-docs.pages.dev/docs/products/opensearch/reference/plugins#list-of-plugins)
https://aiven.atlassian.net/browse/MA-3350
> update: OS plugins links removed

- docs/platform/howto/support.md
> update: instructions for sending HAR files to support

- docs/platform/concepts/permissions.md
> feat: add info on unit-level permissions

- docs/products/clickhouse/reference/limitations.md
- static/includes/clickhouse-storage-limitation.md
https://aiven.atlassian.net/browse/DDB-1983
> update: plans relauch for clickhouse

- docs/products/opensearch/howto/snapshot-credentials.md
- sidebars.ts
Documentation for managing snapshot repository credentials using `custom_keystores` in Aiven for OpenSearch®
> feat: manage snapshot repository credentials

- docusaurus.config.ts
> update: AI disclaimer

- docs/get-started.md
- docs/platform/howto/set-authentication-policies.md
> update: Aiven Platform info

- docs/platform/concepts/billing-and-payment.md
- docs/platform/concepts/orgs-units-projects.md
> update: overview of orgs and units

- static/includes/clouds-list.md
https://aiven.atlassian.net/browse/OPD-292
> feat: exoscale zagrzeb cloud region

- docs/platform/howto/scale-services.md
https://aiven.atlassian.net/browse/DOC-1445
> update: disk size buffer for plan change

- docs/platform/howto/byoc/aws-privatelink-byoc.md
- docs/platform/howto/use-aws-privatelinks.md
- docs/tools/cli/service/privatelink.md
- sidebars.ts
https://aiven.atlassian.net/browse/MILK-426
> feat: aws byoc privatelink

- docs/platform/concepts/free-plan.md
> update: add note about free plan notifications

- docs/platform/howto/saml/add-auth0-idp.md
- docs/platform/howto/saml/add-azure-idp.md
- docs/platform/howto/saml/add-fusionauth-idp.md
- docs/platform/howto/saml/add-google-idp.md
- docs/platform/howto/saml/add-identity-providers.md
- docs/platform/howto/saml/add-jumpcloud-idp.md
- docs/platform/howto/saml/add-okta-idp.md
- docs/platform/howto/saml/add-onelogin-idp.md
> update: SAML troubleshooting

- docusaurus.config.ts
> update: add guidance to Kapa modal and update questions

- docs/platform/howto/manage-payment-card.md
> update: assign card to billing group when adding it

- docs/products/mysql/howto/use-incremental-backups.md
- sidebars.ts
https://aiven.atlassian.net/browse/OPD-305
> feat: mysql incremental backups

- docs/platform/howto/list-marketplace-payments.md
> update: change contact for marketplace setup

- docs/platform/howto/byoc/assign-project-custom-cloud.md
- docs/platform/howto/byoc/create-cloud/create-aws-custom-cloud.md
- docs/platform/howto/byoc/create-cloud/create-google-custom-cloud.md
- docs/platform/howto/byoc/manage-byoc-service.md
[JIRA](https://aiven.atlassian.net/browse/IP-554)
[PREVIEW](https://ip-554-docs-change-contact-f.aiven-docs.pages.dev/docs/platform/howto/byoc/manage-byoc-service#migrate-to-private-byoc)
Remove the account team as a contact for migrating to the priv BYOC model. Advise to create a support ticket.
> update: Replace account team with support ticket for private byoc cloud migration

- docs/tools/aiven-console/howto/create-manage-teams.md
> update: teams deprecation notice

- docs/platform/concepts/rename-services.md
- docs/platform/concepts/service-forking.md
- sidebars.ts
> update: fork a service with terraform

- docs/platform/howto/technical-emails.md
> update: note that users cannot unsubscribe from notifications

- .vscode/aiven.code-snippets
> update: add snippet for brand names

- docs/platform/reference/change-password.md
> fix: password reset instructions

- docs/products/postgresql/reference/pg-connection-limits.md
[JIRA](https://aiven.atlassian.net/browse/BF-3475)
[PREVIEW](https://bf-3475-docs-update-pg-max-c.aiven-docs.pages.dev/docs/products/postgresql/reference/pg-connection-limits)
> update: pg max connections set up

- docs/products/kafka/kafka-connect/concepts/connect-plugin-list-not-available.md
> update: improve connector list troubleshooting page to avoid soft 404

- docs/platform/reference/end-of-life.md
- docs/platform/reference/eol-for-major-versions.md
[JIRA](https://aiven.atlassian.net/browse/BF-3467)
[EOL PREVIEW
](https://bf-3467-docs-update-alloy-db.aiven-docs.pages.dev/docs/platform/reference/end-of-life#aiven-for-alloydb-omni)
[Version support PREVIEW
](https://bf-3467-docs-update-alloy-db.aiven-docs.pages.dev/docs/platform/reference/eol-for-major-versions#aiven-for-alloydb-omni)
> update: alloydb omni EOL

- docs/platform/reference/end-of-life.md
- docs/products/caching.md
- docs/products/caching/get-started.md
- static/includes/eol-caching-banner.md
- static/includes/service-end-of-availability-notice.md
[JIRA](https://aiven.atlassian.net/browse/DDB-2336)
PREVIEW: [Banner](https://ddb-2336-docs-add-aiven-for.aiven-docs.pages.dev/docs/products/caching)
> update: Aiven for Caching EOA/EOL banner

- docs/products/kafka/kafka-connect/howto/gcp-bigquery-sink.md
> update: add cross link

- docs/integrations/send-logs-to-elasticsearch.md
- docs/platform/concepts/service-integration.md
- docs/platform/howto/create-service-integration.md
> update: move service plan limitation for integrations to main page
