docs/platform/howto/list-byoc.md

Fixing the listing page for BYOC

update(platform): format fix in list-byoc

---

docs/products/kafka/kafka-connect/howto/gcp-pubsub-lite-sink.md
docs/products/kafka/kafka-connect/howto/gcp-pubsub-lite-source.md

Fix the link from a help.aiven.io article to point to the Karapace docs.

fix: update help.aiven.io link

---

docs/products/kafka/howto/enable-oidc.md

update: Fixed missing crosslink

---

docs/tools/cli.md

Add instructions for installing Aiven client via Homebrew.

update: CLI instructions with Homebrew installation instructions

---

docs/platform/howto/create-service-integration.md
docs/products/postgresql/howto/report-metrics-grafana.md

The guides to monitor Kafka and PostgreSQL using Aiven prebuilt dashboards, wrongly referenced to create an integration of type Monitor Data in Grafana instead of Grafana Metrics Dashboard.
Fixed it for both service types.

fix: Fixed the guide to monitor metrics on Grafana prebuilt dashboards

---

docs/products/cassandra/howto/use-nosqlbench-with-cassandra.md

Few corrections to reflect changes in new major nosqlbench version 5.

update: nosqlbench instructions for Cassandra

---

docs/tools/terraform.md

Add a link to the Terraform Cookbook to the main TF page on the docs site so that it's easier for customers to find.

update: add link to TF Cookbook

---

docs/tools/aiven-console/howto/create-manage-teams.md

Correct the instruction for migrating from team to groups.

fix: migrate teams instructions

---

docs/products/flink/howto/create-jar-application.md
docs/products/flink/howto/create-sql-application.md
docs/products/flink/howto/restart-strategy-jar-applications.md

update: SQL application to restart strategy

---

docs/products/postgresql/reference/list-of-extensions.md

https://aiven.atlassian.net/browse/BF-2440 + a few editorial fixes

update(postgres): remove deprecated extensions

---

docs/platform/howto/byoc/create-custom-cloud.md

https://aiven.atlassian.net/browse/AD-2227 + editorial updates

update(platform): byoc create custom cloud - wording for deploy template

---

docs/platform/concepts/service_backups.md
docs/products/clickhouse/concepts/features-overview.md
static/_redirects
static/includes/edit-backup-schedule.md

Reduce word count and improve SEO.

update: service backups

---

docs/products/dragonfly/reference/advanced-params.md

Updated the advanced-params.md file to include the import reference link, which was missing.

update: add import ref link

---

docs/platform/concepts/byoc.md
docs/platform/howto/byoc/add-customer-info-custom-cloud.md
docs/platform/howto/byoc/assign-project-custom-cloud.md
docs/platform/howto/byoc/create-custom-cloud.md
docs/platform/howto/byoc/delete-custom-cloud.md
docs/platform/howto/byoc/enable-byoc.md
docs/platform/howto/byoc/rename-custom-cloud.md

https://aiven.atlassian.net/browse/DOC-761
Migrated from https://github.com/aiven/devportal/pull/2461

update(platform): BYOC AWS GA

---

docs/products/mysql/howto/migrate-from-external-mysql.md

Fix formatting of MySQL commands creating a user in source.
Note: untested, because simple formatting change, and leaving this to the people merging.
Link of the page where the bad formatting can be found:
https://aiven.io/docs/products/mysql/howto/migrate-from-external-mysql
Screenshot of the bad formatting:

fix: formatting of MySQL commands

---

docs/products/kafka/kafka-connect/howto/jdbc-sink.md

Updated JDBC sink connector docs to remove delete.enabled configuration flag. 
[DOC-923](https://aiven.atlassian.net/browse/DOC-923)
[DOC-923]: https://aiven.atlassian.net/browse/DOC-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove delete.enable option from JDBC sink connector

---

docs/products/kafka/howto/renew-ssl-certs.md

Added steps for users to disable SSL certificate expiration notifications, especially for services with SASL authentication and no certificate-based authentication.
[DOC-876](https://aiven.atlassian.net/browse/DOC-876)
[DOC-876]: https://aiven.atlassian.net/browse/DOC-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: added info to turn off certificate expiration notification

---

docs/products/kafka/kafka-connect/howto/debezium-source-connector-mongodb.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-pg-node-replacement.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-pg.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-sql-server.md
static/includes/debezium-breakingchange.md

Updated Debezium source connector documentation to reflect breaking changes introduced in Debezium version 2.5. 
[HH-3411](https://aiven.atlassian.net/browse/HH-3411)
[HH-3411]: https://aiven.atlassian.net/browse/HH-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Debezium v2.5 breaking changes

---

SECURITY.md

Our bugbounty program is now with Bugcrowd. The HackerOne program is deprecated.

fix: change bugbounty provider from h1 to bugcrowd

---

docs/products/dragonfly/howto/compatibility-redisjson.md
sidebars.ts

Added content for RedisJSON’s v2 JSONPath syntax compatibility with Aiven for Dragonfly.
[DOC-806](https://aiven.atlassian.net/browse/DOC-806)
[DOC-806]: https://aiven.atlassian.net/browse/DOC-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: RedisJSON v2 syntax compatibility

---

docs/platform/concepts/orgs-and-units.md
docs/platform/concepts/projects.md
sidebars.ts

Move project related docs to orgs and projects section and add another level to that section to group these docs.

update: structure of orgs and access docs

---

docs/marketplace-setup.md

Fix link to Aiven on AWS Marketplace.

fix: link to AWS Marketplace

---

docs/platform/concepts/free-plan.md

It was pointed out at https://aiven.io/community/forum/t/free-plan-postgresql-getting-moved-to-digital-ocean-docs-say-aws/751/3?u=aiven_angie that our free tier docs currently list incorrect region availability. This list as it stands requires manual updates and it's hard for us to remember to do so.
Proposed resolution: Instead, link to the DigitalOcean section of https://aiven.io/docs/platform/reference/list_of_clouds so that the canonical list is the point of reference.

fix: remove inaccurate list of free tier regions

---

docs/platform/concepts/managed-users.md

Fix the introduction to the managed users doc as authentication policies can be set for all org users, not just managed users.

fix: managed users introduction

---

docs/platform/howto/create_new_service_user.md
src/components/ConsoleIcons/index.tsx

* Fixed the users icon
* Fixed the copy for the application users icon
* Added Groups

fix: icons for users, app users, and groups

---

docs/platform/howto/saml/add-okta-idp.md

Okta integration uses SAML 2.0, not 1.0. Some other minor changes for readability.

fix: okta idp instructions

---

docs/products/opensearch/howto/custom-dictionary-files.md
docs/products/opensearch/howto/set_index_retention_patterns.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

OS Custom dictionary upload features allow customers to upload certain text files and run queries against it. 
[DOC-854](https://aiven.atlassian.net/browse/DOC-854)
[DOC-854]: https://aiven.atlassian.net/browse/DOC-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Custom dictionary files for OS

---

.gitignore
docs/products/clickhouse/reference/supported-input-output-formats.md

The comment must have slipped in by mistake and shouldn't be in the article.
Also ignore some IDE files for contributors.

fix: remove extra comment in supported ClickHouse IO formats

---

docs/products/flink/concepts/checkpoints.md
docs/products/flink/concepts/event-processing-time.md
docs/products/flink/concepts/kafka-connector-requirements.md
docs/products/flink/concepts/watermarks.md
docs/products/flink/concepts/windows.md
docs/products/flink/howto/connect-pg.md
docs/products/kafka/howto/flink-with-aiven-for-kafka.md

Updated links referring to Apache Flink® documentation from v1.15 to v1.16 and aligned content with the style guide and format.
[HH-1604](https://aiven.atlassian.net/browse/HH-1604)
[HH-1604]: https://aiven.atlassian.net/browse/HH-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Flink ref doc link version to 1.16

---

docs/platform/concepts/hourly-billing-model.md
docs/platform/howto/billing-assign-projects.md
docs/platform/howto/change-billing-contact.md
docs/platform/howto/create-billing-groups.md
docs/platform/howto/list-billing.md
docs/platform/howto/update-tax-status.md
docs/platform/howto/use-billing-groups.md
sidebars.ts
static/_redirects

This changes the super admin notice to be clear
that the sections cannot be accessed in the Console and also adds details on the billing main page
about the differences in Console and API access to some billing information.

update: billing permissions

---

docs/products/flink/howto/create-integration.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

Updated side nav link for Aiven for Apache Flink applications to point to /howto/create-flink-applications

update: modified TOC link for Flink applications page

---

docs/platform/concepts/billing-groups.md

Clarify that access to billing groups requires super admin access in the Console specifically.

fix: clarify permissions for billing groups access

---

docs/platform/howto/saml/add-okta-idp.md

Change attribute statements for Okta config.

update: Okta attribute statements

---

docs/platform/concepts/enhanced-compliance-env.md

Remove Aiven Enterprise as a requirement.

update: remove AE from ECE doc

---

docs/platform/howto/saml/add-okta-idp.md

update: remove attributes from Okta configuration

---

docs/products/flink/howto/upgrade-flink-version.md
sidebars.ts

Added content on the upgrade process and limitations for Aiven for Apache Flink and Flink applications.

add: Apache Flink upgrade process and limitations

---

docs/platform/concepts/byoc.md
docs/platform/howto/byoc/assign-project-custom-cloud.md
docs/platform/howto/byoc/create-custom-cloud.md
docs/platform/howto/byoc/enable-byoc.md

Swapping "contact sales" for "contact your account team"

update(platform): BYOC contact sales replacement and editorial fixes

---

docs/products/postgresql/reference/pg-connection-limits.md

Add max_connections for free plan, based on querying it in a PG 16 instance.
Note administrative reservation (res_for_super = 3) and potential use by replication.
(I lack the privileges to determine whether Aiven's replication uses superuser, or is a separate allocation.)

update(postgresql): connection limits with free plan limit/platform usage

---

src/components/ConsoleIcons/index.tsx

Replace files step missing replace file icon. 
https://aiven.io/docs/products/opensearch/howto/custom-dictionary-files#replace-files

update: Missing label for file replacement action

---

docs/platform/howto/manage-project.md
src/components/ConsoleIcons/index.tsx

Updates instructions for new option to move a project to a different organization. 
Cleans up the other text and adds icons.

update: moving projects to other orgs

---

docs/products/kafka/howto/datadog-customised-metrics.md
docs/products/kafka/kafka-mirrormaker/howto/datadog-customised-metrics.md
sidebars.ts

The syntax provided by the documentation fails with error `no matches found` and a new custom metric was added for mm.
[DOC-1054]
[EC-324]
[DOC-1054]: https://aiven.atlassian.net/browse/DOC-1054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EC-324]: https://aiven.atlassian.net/browse/EC-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: CLI service integration-update fails adding custom metrics

---

docs/products/kafka/concepts/configuration-backup.md

This pull request addresses gaps and clarifies expectations in the Aiven for Apache Kafka® configuration backups documentation ([HH-3838](https://aiven.atlassian.net/browse/HH-3838)).
[HH-3838]: https://aiven.atlassian.net/browse/HH-3838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: improve content for Kafka configuration backup

---

docs/platform/concepts/service_backups.md

This pull request updates docs to reflect the current behavior of Redis Persistence, specifically regarding the deletion of all existing backups when persistence is switched off.
[DOC-1023](https://aiven.atlassian.net/browse/DOC-1023)
[DOC-1023]: https://aiven.atlassian.net/browse/DOC-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: information about persistence for Caching service backup

---

docs/platform/howto/byoc/download-infrastructure-template.md
docs/tools/cli/byoc.md

fix(platform): BYOC typos

---

docs/products/kafka/concepts/upgrade-procedure.md

Improve Apache Kafka® upgrade procedure documentation for clarity and consistency.
[DOC-1070](https://aiven.atlassian.net/browse/DOC-1070)
[DOC-1070]: https://aiven.atlassian.net/browse/DOC-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Improved Kafka upgrade procedure content

---

docs/products/clickhouse/howto/connect-with-go.md
docs/products/clickhouse/howto/connect-with-java.md
docs/products/clickhouse/howto/connect-with-nodejs.md
docs/products/clickhouse/howto/connect-with-python.md
sidebars.ts

fix: clickhouse spelling

---

docs/platform/howto/byoc/create-custom-cloud.md

fix(platform): remove "destroy terraform" from create custom cloud instructions

---

docs/platform/concepts/backup-to-another-region.md
docs/platform/howto/btar/disable-backup-to-another-region.md
docs/platform/howto/btar/enable-backup-to-another-region.md
docs/platform/howto/btar/manage-backup-to-another-region.md

BTAR is back to LA from GA. Bringing back the relevant info.
https://aiven.atlassian.net/browse/AD-2586

update(platform): bring back LA for BTAR

---

static/_redirects

Fix redirect for support topic. The support centre link in this [article](https://aiven.io/support-services) points to an older support page.

fix: Redirect for support topic

---

docs/products/cassandra/howto/connect-python.md

Just a minor change to align the documented variable name `SSL_CERTFILE` with the placeholder in the code. Noticed when I did a Ctrl^C on the web page - with no hits.
Could as well be done the other way around of course, by rather changing the variable name in the code example.
- [ X] The first paragraph of the page is on one line.
- [ X] The other lines have a line break at 90 characters.
- [ -] I checked the output.
- [ X] I applied the [style guide](../styleguide.md).
- [ X] My links start with `/docs/`.

fix: match variable names with variable placeholder

---

docs/products/clickhouse/concepts/disaster-recovery.md
docs/products/clickhouse/howto/create-dictionary.md
sidebars.ts

https://aiven.atlassian.net/browse/DDB-1026

add(clickhouse): create dictionaries

---

docs/products/metrics/concepts.md

fix: metrics typo

---

docs/products/clickhouse/get-started.md

Final tweaks to the recently published Getting started improvements

fix(clickhouse): getting started

---

docs/products/metrics/howto/migrate-influxdb-thanos.md
docs/products/metrics/howto/migrate-m3db-thanos.md
sidebars.ts

Add documentation for migrating Aiven for M3DB and Aiven for InfluxDB databases to Aiven for Thanos Metrics, including compatibility considerations and step-by-step migration instructions.

add: InfluxDB and M3DB migration to Thanos Metrics

---

docs/products/clickhouse/howto/create-dictionary.md

Our SAs found some behaviour caused by this setting confusing.
https://aiven-io.slack.com/archives/C029BCC75K7/p1721117304789959?thread_ts=1721042188.692799&cid=C029BCC75K7

update(clickhouse): mention dictionaries_lazy_load = true setting

---

docs/products/kafka/kafka-connect/howto/enable-connect.md

Updates the instructions to reflect current and planned UI changes for this feature.

fix: enable Kafka Connect on a Kafka service

---

docs/products/kafka/concepts/follower-fetching.md
docs/products/kafka/howto/enable-follower-fetching.md
sidebars.ts

Added documentation for enabling follower fetching in Aiven for Apache Kafka. [HH-4055](https://aiven.atlassian.net/browse/HH-4055)
[HH-4055]: https://aiven.atlassian.net/browse/HH-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Follower fetching in Kafka

---

docs/platform/howto/set-authentication-policies.md
docs/platform/howto/user-2fa.md
src/components/ConsoleIcons/index.tsx

Adds details on what the 2FA setting applies to in auth policies.

add: details on 2FA

---

docs/platform/reference/eol-for-major-versions.md
sidebars.ts

https://aiven.atlassian.net/browse/DOC-1111
- Promoting the EoL article in the doc architecture to improve its accessibility.
- Removing it from the "Service management" section coz it includes not only services EoL dates but also dev tools EoL info.
- Moving the article upwards in the hierarchy under the "Platform" area due to its cross-domain character.

update(platform): promote the EoL for services and tools versions article

---

docs/products/cassandra/howto/connect-cqlsh-cli.md

Fixed a typo and made some minor editorial improvements

fix(cassandra): connect via cqlsh - fixes and improvements

---

docs/products/kafka/howto/enable-governance.md

Users can continue to create new topics within their Aiven for Apache Kafka service even with Governance enabled. However, when claiming ownership of a topic, Governance introduces a request-and-approval flow.

fix: impact of govenanace topic creation

---

docs/products/mysql/howto/do-check-service-migration.md

fix(mysql): duplicated parameter in the check migration commands

---

docusaurus.config.ts
src/plugins/svg-fix/index.ts

SVGs, by default do not use unique prefix ids and share certain fill definitions incorrectly. This plugin makes sure they use unique prefix ids.

fix: use unique svg ids

---

sidebars.ts

Somehow the byoc networking & sec doc landed in a weird place. Fixing that...

fix(platform): move byoc networking and security doc to the byoc section

---

docs/products/mysql/concepts/high-availability-mysql.md
docs/products/mysql/concepts/high-availability.md
docs/products/postgresql/concepts/high-availability.md
sidebars.ts

https://aiven.atlassian.net/browse/DOC-675

add(mysql postgresql): high availability information

---

docs/products/kafka/concepts/kafka-tiered-storage.md
docs/products/kafka/concepts/tiered-storage-guarantees.md
docs/products/kafka/concepts/tiered-storage-how-it-works.md
docs/products/kafka/concepts/tiered-storage-limitations.md
docs/products/kafka/howto/configure-topic-tiered-storage.md
docs/products/kafka/howto/create-topic.md
docs/products/kafka/howto/create-topics-automatically.md
docs/products/kafka/howto/enable-kafka-tiered-storage.md
docs/products/kafka/howto/kafka-tiered-storage-get-started.md
docs/products/kafka/howto/tiered-storage-overview-page.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-mongodb.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-pg.md
docs/products/kafka/kafka-connect/howto/debezium-source-connector-sql-server.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

- Removed Early Availability tags from Kafka tiered storage content.
- Updated the Pricing section in the overview topic to include details about tiered storage charges.

fix: Kafka tiered storage GA

---

docs/products/kafka/kafka-connect/howto/ibm-mq-sink-connector.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

Content for how to create an IBM MQ sink connector in Aiven for Apache Kafka/Aiven for Apache Kafka Connent. 
Ref: https://aiven.atlassian.net/browse/EC-419

add: Content for IBM MQ sink connector

---

docs/products/metrics.md
docs/products/metrics/concepts.md
docs/products/metrics/concepts/retention-rules.md
docs/products/metrics/concepts/storage-resource-scaling.md
docs/products/metrics/howto/list-data-migration.md

Remove the registered trademark symbol (®) from all mentions of "Aiven for Metrics" in our documentation. Since the 
service name is not currently registered, and there are no plans to register it in the near future. 
https://aiven.atlassian.net/browse/DOC-1139

fix: remove trademark for Aiven for Metrics

---

docs/products/postgresql/howto/migrate-aiven-db-migrate.md

Fixes the broken link to the upstream docs.

fix: broken link to pg docs

---

docs/products/clickhouse/concepts/data-integration-overview.md
docs/products/clickhouse/howto/copy-data-across-instances.md
docs/products/clickhouse/howto/data-service-integration.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

https://aiven.atlassian.net/browse/DOC-686
Migrated from https://github.com/aiven/devportal/pull/2442

add(clickhouse): credentials integration

---

docs/products/kafka/howto/prevent-full-disks.md
src/components/ConsoleIcons/index.tsx

Critical threshold for denying writes to Apache Kafka broker is currently defined at 95% not 97% disk usage.
https://aiven.io/docs/products/kafka/howto/prevent-full-disks
[PM-4272]
[PM-4272]: https://aiven.atlassian.net/browse/PM-4272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Kafka disk write lock triggers at 95% not 97%

---

docs/products/kafka/kafka-connect/howto/snowflake-sink-prereq.md

I assume mentioning BigQuery in the Snowflake sink connector (Apache Kafka Connect) is a copy & paste mistake.

fix: replace BigQuery reference in snowflake-sink-prereq.md

---

docs/products/clickhouse/reference/supported-table-engines.md

Also add a note for using integration engines and dictionaries with managed crentials integrations.

update: Table engines supported by ClickHouse

---

docs/products/kafka/kafka-connect/reference/connect-metrics-prometheus.md

Added missing Kafka Connect metrics
[DOC-917](https://aiven.atlassian.net/browse/DOC-917)
[DOC-917]: https://aiven.atlassian.net/browse/DOC-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: missing connector metrics

---

docs/products/kafka/howto/kafdrop.md

Fix Kafdrop Docker instructions to include Mac M1 chip compatibility and clarify setup steps.
[DOC-916](https://aiven.atlassian.net/browse/DOC-916)
[DOC-916]: https://aiven.atlassian.net/browse/DOC-916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Kafdrop instructions for Mac users

---

docs/products/kafka/howto/enabled-consumer-lag-predictor.md

Add some example PromQL queries that could be useful starting points for lag predictor metrics usage.

add: kafka lag predictor metrics example [HH-2562]

---

.github/PULL_REQUEST_TEMPLATE.md

fix: styleguide link in template

---

docs/products/kafka/howto/enabled-consumer-lag-predictor.md

Remove extra quotes for the command.

fix: promql command

---

docs/products/kafka/kafka-connect/howto/configure-aws-secrets-manager.md
docs/products/kafka/kafka-connect/howto/configure-hashicorp-vault.md
docs/products/kafka/kafka-connect/howto/configure-secret-providers.md
sidebars.ts

Added content for configuring AWS Secrets Manager and HashiCorp Vault as secret providers in Apache Kafka Connect on Aiven, including examples for JDBC connectors.
Ref: [EC-343](https://aiven.atlassian.net/browse/EC-343)
[EC-343]: https://aiven.atlassian.net/browse/EC-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Configure secret providers for Apache Kafka Connect

---

docs/products/opensearch/howto/migrating_elasticsearch_data_to_aiven.md

Fixes and improvements for the Elasticsearch to Aiven for OpenSearch® migration process.

fix: CLI command for Elasticsearch migration to OS

---

docs/platform/concepts/backup-to-another-region.md
docs/platform/howto/btar/enable-backup-to-another-region.md

Added OpenSearch to the list of supported services for Backup to Another Region (BTAR).
NOTE: due to the merge freeze, the prod update is pending.

add: OpenSearch to BTAR list

---

docs/products/opensearch/howto/migrate-opendistro-security-config-aiven.md
docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md

Added a note to exclude the `.opendistro_security` index pattern from snapshot restore in the migration documentation.

add: note to exclude index pattern

---

docs/platform/howto/okta-user-provisioning-with-scim.md

Adds a warning to not select the import groups configuration.

update: SCIM config for Okta

---

docs/products/opensearch/howto/migrate-snapshot-data-opensearch.md

Updated the documentation to provide a method for verifying document counts after migration.

update: added method to get document count for migrated data

---

docs/platform/concepts/enhanced-compliance-env.md

Migrate to ECE -chapter had a duplicated sentence.

fix: Remove duplicate sentence from ECE description page

---

docs/products/kafka/howto/enable-follower-fetching.md

Added missing icon in the steps

fix: missing icon

---

docs/products/cassandra/howto/zdm-proxy.md

fix(cassandra): broken link to ZDM migration intro

---

docs/products/grafana/howto/dashboard-previews.md

Fixed typo and improved documentation style for Grafana dashboard previews.

fix: typo in Grafana dashboard previews documentation

---

docs/products/kafka/kafka-connect/howto/configure-aws-secrets-manager.md
docs/products/kafka/kafka-connect/howto/configure-hashicorp-vault.md

Updated Aiven for Apache Kafka® Connect secret providers documentation to include steps for Terraform.

update: Secrete providers configuration via Terraform

---

docs/products/grafana/reference/plugins.md

Removed deprecated plugins from the Grafana plugin list and added missing links for the data source and panel plugins.

update: Remove deprecated Grafana plugins

---

docs/products/kafka/kafka-connect/howto/gcp-pubsub-source.md

Updated Google Pub/Sub connector documentation to clarify required IAM roles and added error handling information for PERMISSION_DENIED during subscription verification.
[EC-524](https://aiven.atlassian.net/browse/EC-524)
[EC-524]: https://aiven.atlassian.net/browse/EC-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Google Pub/Sub connector details and IAM roles

---

docs/products/kafka/howto/enabled-consumer-lag-predictor.md

Added configuration details for kafka_lag_predictor.topics and kafka_lag_predictor.group_filters, with examples, to clarify how to filter topics and consumer groups in lag prediction.
[HH-4519](https://aiven.atlassian.net/browse/HH-4519)
Preview - https://harshini-topic-whitelist-fil.aiven-docs.pages.dev/docs/products/kafka/howto/enabled-consumer-lag-predictor
[HH-4519]: https://aiven.atlassian.net/browse/HH-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: added topic filtering configuration for lag predictor

---

docs/tools/kubernetes.md

fix: broken link for K8s docs

---

docs/integrations/cloudwatch/cloudwatch-logs-cli.md

fix(integrations): typo in ACL permission

---

docs/tools/kubernetes.md

Updates main K8s page with links to main operator docs and removes the installation instructions (which are available in the Aiven Operator docs). Some other improvements to the content and example.

update: operator docs

---

docs/platform/concepts/free-plan.md

Removes DO from the free plan doc as it will no longer be offered on new free plans.

update: remove cloud providers from free plan

---

docs/tools/cli/service-cli.md

`avn service cli` also supports connecting to an Aiven for Valkey service.
It connects to Valkey or Redis using whichever of `valkey-cli` or `redis-cli` is available (validated by trying it out!), but I think it's more useful to reference `valkey-cli` (only) in the text (it does say "such as"), especially as that will make it simpler to remove mention of Aiven for Caching when that is retired.

fix: `avn service cli` also support Valkey

---

docs/platform/concepts/free-plan.md

We no longer support a free plan for Aiven for Caching, we do for Aiven for Valkey, so replace the terms.
Note: I assume that the `maxmemory` limitation is retained as-is.

fix: free plan page should name Valkey

---

docs/products/valkey/get-started.md
docs/products/valkey/howto/connect-python.md
docs/products/valkey/howto/connect-valkey-cli.md
sidebars.ts

Add the missing page describing how to connect to Aiven for Valkey™ using `valkey-cli`. This is very similar to the equivalent page for Aiven for Caching and `redis-cli`.
This page will be needed by the developer center articles that I am changing to mention Aiven for Valkey instead of Aiven for Caching.
1. Added the missing page
2. Linked to it from docs/products/valkey/get-started.md and also fixed the links on that page which still pointed to `/docs/products/caching` so that they now point to `/docs/products/valkey`
3. Added entry in `sidebars.ts` - it's not obvious from the comments at the top if this is necessary, but it seems consistent with current usage
4. In the "Connect with Python" page, correct the capitalisation of `valkey-python` in the link at the end

add: howto page for valkey-cli

---

docs/products/kafka/howto/best-practices.md

Add information about Single AZ Kafka for cost optimisation for Bring Your Own Cloud customers

update: add information about single availability zone for Kafka

---

docs/products/valkey/howto/migrate-caching-valkey-to-aiven-for-valkey.md
sidebars.ts

Added migration process from Aiven for Caching or Valkey to Aiven for Valkey.
[MA-3046](https://aiven.atlassian.net/browse/MA-3046)
[MA-3046]: https://aiven.atlassian.net/browse/MA-3046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Migration from Caching to Valkey

---

docs/products/mysql/concepts/mysql-tuning-and-concurrency.md

While scrolling through the docs, I noticed a typo in the sidebar label of `docs/products/mysql/concepts/mysql-tuning-and-concurrency.md`. The label was "Tuning foor concurrency," and I corrected it to "Tuning for concurrency". This is my first time contributing here, so if the commit or PR title is incorrect or if something is missing, I'm more than happy to make any necessary adjustments.

fix: typo in sidebar label

---

docs/tools/terraform/howto/migrate-from-teams-to-groups.md

Updates teams to groups migration instructions to use the new `aiven_organization_permission` resource.

update: use permission resource in teams migration

---

docs/products/kafka/concepts/kafka-tiered-storage.md

Remove duplicate information based on feedback.

fix: remove duplicate content in Kafka tiered storage overview

---

docs/products/kafka/howto/create-topics-automatically.md

Clarify default behavior of automatic topic creation in Aiven for Apache Kafka. 
[DOC-1206](https://aiven.atlassian.net/browse/DOC-1206)
[DOC-1206]: https://aiven.atlassian.net/browse/DOC-1206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: default behavior of automatic topic creation

---

docs/integrations/cloudlogging.md

A customer tried to use cross project service account, but it cause auth error.
It turns out journalpump extracts project id from the credential and use it as the target project.
ZD: https://aivenhelp.zendesk.com/agent/tickets/91867

update: google cloud logging integration

---

docs/products/dragonfly/howto/migrate-aiven-caching-df-console.md
docs/products/dragonfly/howto/migrate-ext-redis-df-console.md
static/includes/dragonfly-limitations.md

Add Valkey to migration documentation and update migration steps for clarity.
[MA-3062](https://aiven.atlassian.net/browse/MA-3062)
[MA-3062]: https://aiven.atlassian.net/browse/MA-3062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: add Valkey to Dragonfly migration documentation

---

docs/platform/reference/get-resource-IDs.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

IDs like organization ID, user ID, etc., are often needed by customers for working with dev tools like Terraform. In addition, having these IDs can make it easier for support to investigate an issue. At the moment, not all IDs are easily found in Console, but there are still ways to get them.

update: add instructions for getting resource IDs

---

docs/products/clickhouse/howto/integrate-kafka.md
docs/products/kafka/kafka-connect/howto/clickhouse-sink-connector.md

https://aiven.atlassian.net/browse/DDB-1374

add(clickhouse kafka): cross link btw clickhouse sink connector and kafka engine integration

---

docs/platform/howto/use-aws-privatelinks.md

https://aiven.atlassian.net/browse/MILK-367

update(aws-privatelink): add mirrormaker as not supported for aws privatelink

---

docs/platform/howto/download-invoices.md
sidebars.ts

Adds instructions for downloading invoices in the Console.

add: instructions for downloading invoices

---

docs/platform/concepts/service_backups.md

The parameter is in "Backups -> Configure backup settings" not "Service Settings-> Advanced configurations"

update: correct the loc of redis_persistence setting

---

docs/platform/concepts/tax-information.md
docs/platform/howto/payment-methods.md

Change references to the sales team email address to the billing team's email for billing requests.

update: replace sales team address with billing team's email

---

docs/products/kafka/kafka-connect/howto/kafka-connect-debezium-tls-pg.md

Remove LA [EC-224](https://aiven.atlassian.net/browse/EC-224)
[EC-224]: https://aiven.atlassian.net/browse/EC-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: remove LA tag from Kafka Connect with PostgreSQL integration

---

.github/vale/styles/Aiven/Headings.yml
docs/get-started.md
docs/platform/concepts/application-users.md
docs/platform/concepts/enhanced-compliance-env.md
docs/platform/concepts/free-plan.md
docs/platform/concepts/free-trial.md
docs/platform/concepts/permissions.md
docs/platform/howto/byoc/create-custom-cloud.md
docs/platform/howto/disk-autoscaler.md
docs/platform/howto/migrate-services-vpc.md
docs/platform/howto/set-authentication-policies.md
docs/platform/reference/eol-for-major-versions.md
docs/products/caching.md
docs/products/cassandra/get-started.md
docs/products/clickhouse/get-started.md
docs/products/flink/howto/upgrade-flink-version.md
docs/products/grafana.md
docs/products/grafana/concepts/grafana-features.md
docs/products/kafka/howto/enable-follower-fetching.md
docs/products/kafka/kafka-connect/howto/configure-aws-secrets-manager.md
docs/products/kafka/kafka-connect/howto/configure-hashicorp-vault.md
docs/products/kafka/karapace/howto/manage-schema-registry-authorization.md
docs/products/opensearch/concepts/opensearch-security-considerations.md
docs/products/opensearch/concepts/os-security.md
docs/products/opensearch/howto/enable-opensearch-security.md
docs/products/opensearch/howto/setup-cross-cluster-replication-opensearch.md
docs/tools/kubernetes.md
docs/tools/terraform/get-started.md
sidebars.ts
src/components/HomepageFeatures/index.tsx

update: align Terraform and Kubernetes naming with brand guidelines

---

docs/products/kafka/reference/kafka-metrics-prometheus.md
docs/products/opensearch/howto/os-metrics.md
sidebars.ts
static/includes/host-metrics.md

Add documentation for view Aiven for OpenSearch metrics via Prometheus.
[MA-3109](https://aiven.atlassian.net/browse/MA-3109)
preview - https://harshini-os-metrics-promethe.aiven-docs.pages.dev/docs/products/opensearch/howto/os-metrics
[MA-3109]: https://aiven.atlassian.net/browse/MA-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Metrics for OpenSearch via Prometheus

---

docs/platform/concepts/byoc.md
docs/platform/howto/byoc/create-custom-cloud.md
docs/platform/howto/byoc/enable-byoc.md

https://aiven.atlassian.net/browse/MILK-388

update(BYOC): remove OCI and Azure providers from the BYOC docs

---

docs/products/flink/howto/ext-kafka-flink-integration.md
docs/tools/cli/service/integration.md

The documentation mistakenly suggested to pass a path to SSL key/cert when calling ServiceIntegrationEndpointCreate via API or CLI. Moreover the format of these values should match RFC-1421.
[EH-1434 ](https://aiven.atlassian.net/browse/EH-1434)
[DOC-1245](https://aiven.atlassian.net/browse/DOC-1245)
[EH-1434]: https://aiven.atlassian.net/browse/EH-1434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1245]: https://aiven.atlassian.net/browse/DOC-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Format of key/cert upon creation of ext kafka integration endpoint

---

docs/products/kafka/kafka-connect/reference/advanced-params.md

Fixed typo in the Kafka Connect advanced parameter topic title.

fix: Typo in title

---

docs/tools/cli/service-cli.md
docs/tools/cli/service/acl.md
docs/tools/cli/service/kafka-acl.md
sidebars.ts

Add documentation for the new commands for managing Apache Kafka native ACLs.
Also fix little typo in `docs/tools/cli/service/acl.md`.

add: CLI for managing Apache Kafka native ACLs

---

docs/products/kafka/kafka-mirrormaker/howto/exactly-once-delivery.md
sidebars.ts
src/components/ConsoleIcons/index.tsx

Added content for exactly-once delivery configuration for Aiven for Kafka MirrorMaker 2. 
Preview - https://harshini-mm2-exactly-once-de.aiven-docs.pages.dev/docs/products/kafka/kafka-mirrormaker/howto/exactly-once-delivery
[EC-446](https://aiven.atlassian.net/browse/EC-446)
[EC-446]: https://aiven.atlassian.net/browse/EC-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Exactly-once delivery for MM2

---

docs/products/kafka/kafka-mirrormaker/troubleshooting/topic-not-replicated.md
docusaurus.config.ts
sidebars.ts

Create a new menu section dedicated to troubleshooting MirrorMaker, along with first guide "Why are some topics or partitions not replicated"
[DOC-1212]
Page preview - https://jclarysse-add-mirrormaker-tr.aiven-docs.pages.dev/docs/products/kafka/kafka-mirrormaker/troubleshooting/topic-not-replicated
[DOC-1212]: https://aiven.atlassian.net/browse/DOC-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: MirrorMaker troubleshooting section and first guide

---

docs/products/kafka/kafka-mirrormaker/troubleshooting/topic-not-replicated.md

Fixed the formatting for the parameters.

fix: Parameter formatting

---

docs/products/kafka/howto/datadog-customised-metrics.md

It is not clear that at least one value for `include_consumer_groups` is required for `exlude_topics` to apply.
[DOC-1256]
[DOC-1256]: https://aiven.atlassian.net/browse/DOC-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: kafka topic exclusion conditions for datadog

---

docs/platform/reference/end-of-life.md
docs/platform/reference/eol-for-major-versions.md

- Removed M3DB from the end of major version topic.  
- Clarified the ability to create new Aiven for M3DB services based on whether the project already includes an existing service.
[DOC-1259](https://aiven.atlassian.net/browse/DOC-1259)
[DOC-1259]: https://aiven.atlassian.net/browse/DOC-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: clarify M3DB service creation rules based on project inclusion

---

docs/products/valkey/get-started.md

Add missing link for Java under "Connect to Aiven for Valkey" section

add: howto link for Java

---

docs/products/clickhouse/concepts/clickhouse-tiered-storage.md
docs/products/clickhouse/howto/local-cache-tiered-storage.md
sidebars.ts

https://aiven.atlassian.net/browse/DDB-1514

add(clickhouse): local on-disk cache for remote files

---

docs/products/clickhouse/concepts/data-integration-overview.md
docs/products/clickhouse/reference/supported-table-engines.md
docs/products/clickhouse/reference/supported-table-functions.md

https://aiven.atlassian.net/browse/DDB-1539

add(clickhouse): azureBlobStorage table engine and function

---

docs/products/opensearch/howto/setup-cross-cluster-replication-opensearch.md
yarn.lock

Add steps to promote a follower service to standalone for Aiven for OpenSearch. 
Preview - https://harshini-os-promote-follower.aiven-docs.pages.dev/docs/products/opensearch/howto/setup-cross-cluster-replication-opensearch
[MA-3146](https://aiven.atlassian.net/browse/MA-3146)
[MA-3146]: https://aiven.atlassian.net/browse/MA-3146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: Promote follower to standalone OS service

---

docs/products/kafka/kafka-mirrormaker/howto/log-analysis-offset-sync-tool.md

Clarify offset sync behavior in MirrorMaker 2 docs.
[EC-678](https://aiven.atlassian.net/browse/EC-678)
[EC-678]: https://aiven.atlassian.net/browse/EC-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: clarify offset sync behavior in MirrorMaker 2

---

docs/products/metrics/concepts/storage-resource-scaling.md

Update Thanos tiered storage docs to clarify mandatory usage, align with other offerings, and include cost details.
[MA-3185](https://aiven.atlassian.net/browse/MA-3185)
Preview: https://harshini-metrics-storage-upd.aiven-docs.pages.dev/docs/products/metrics/concepts/storage-resource-scaling
[MA-3185]: https://aiven.atlassian.net/browse/MA-3185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Storage information for Thanos to include tiered storage

---

docs/platform/reference/eol-for-major-versions.md

Cassandra 4.0 EoL and EoA dates were extended, but we missed updating the docs in https://aiven.atlassian.net/browse/DDB-1055. Fix with the correct dates.

update: cassandra 4.0 EoL and EoA dates

---

docs/products/opensearch/get-started.md
src/components/non-swizzled/ConsoleIcons/index.tsx
yarn.lock

Preview - https://harshini-os-get-started-upda.aiven-docs.pages.dev/docs/products/opensearch/get-started

update: OpenSearch get started updates

---

docs/products/metrics/howto/migrate-m3db-thanos.md

Adds a link to the migration guide for Terraform resources and fixes one UI label in the instructions.

update: link to TF migration instructions for M3 to Thanos

---

docs/products/caching/howto/upgrade-aiven-for-caching-to-valkey.md
docs/products/valkey/howto/migrate-caching-valkey-to-aiven-for-valkey.md

https://aiven.atlassian.net/browse/DDB-1605

add(valkey): migrate to Aiven for Valkey via k8

---

docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md
sidebars.ts

Add content for Iceberg sink connector to Apache Kafka Connect for real-time data ingestion into Iceberg tables.
- Support for AWS Glue as REST Catalog and AWS Glue Catalog.
[KCON-80](https://aiven.atlassian.net/browse/KCON-80)
Preview - https://harshini-iceberg-sink-connec.aiven-docs.pages.dev/docs/products/kafka/kafka-connect/howto/iceberg-sink-connector
[KCON-80]: https://aiven.atlassian.net/browse/KCON-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Iceberg sink connector to Apache Kafka Connect

---

docs/platform/concepts/service_backups.md
docs/products/m3db.md
docs/products/m3db/get-started.md

- Added a note about M3DB deprecation.  
- Removed references to M3DB in the service backup table. 
[MA-3203](https://aiven.atlassian.net/browse/MA-3203)
[DOC-1298](https://aiven.atlassian.net/browse/DOC-1298)
[MA-3203]: https://aiven.atlassian.net/browse/MA-3203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1298]: https://aiven.atlassian.net/browse/DOC-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Added note about M3 deprecation

---

docs/products/kafka/reference/kafka-metrics-prometheus.md

Clarifies the removal of certain metrics in KRaft mode for Aiven for Apache Kafka®. Ensures only relevant metrics are exposed, aligning with the transition from ZooKeeper to KRaft.  
- [HH-4865](https://aiven.atlassian.net/browse/HH-4865)  
- [#56370](https://github.com/aiven/aiven-core/pull/56370)  
- [DOC-1317](https://aiven.atlassian.net/browse/DOC-1317)
[HH-4865]: https://aiven.atlassian.net/browse/HH-4865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1317]: https://aiven.atlassian.net/browse/DOC-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: clarify KRaft metrics removal

---

.vscode/aiven.code-snippets
docs/platform/concepts/beta_services.md
docs/platform/concepts/enhanced-compliance-env.md
docs/platform/howto/custom-plans.md
docs/platform/howto/list-marketplace-payments.md
docs/products/cassandra/howto/enable-cross-cluster-replication.md
docs/products/cassandra/howto/list-cross-cluster-replication.md
docs/products/cassandra/howto/manage-cross-cluster-replication.md
docs/products/flink/howto/create-flink-applications.md
docs/products/flink/howto/create-jar-application.md
docs/products/kafka/howto/enable-governance.md
docs/products/kafka/howto/enabled-consumer-lag-predictor.md

Replaced references to sales@aiven.io with http://aiven.io/contact, as the email is no longer in use.

fix: Sales email address in docs

---

docs/products/clickhouse/reference/limitations.md

fix: reducing the number of nodes is now possible

---

docs/platform/concepts/backup-to-another-region.md
docs/platform/howto/btar/disable-backup-to-another-region.md
docs/platform/howto/btar/enable-backup-to-another-region.md
docs/platform/howto/btar/manage-backup-to-another-region.md
sidebars.ts

https://aiven.atlassian.net/browse/AD-3009

feat: Point in time recovery (PITR) for BTAR

---

docs/products/postgresql/reference/pg-connection-limits.md

fix: remove cloud providers from PG max connections list

---

docs/integrations/datadog.md
docs/integrations/datadog/datadog-metrics.md
docs/products/kafka/howto/datadog-customised-metrics.md
static/includes/startup-plan-datadog.md

Update docs to reflect Datadog integration removal for new startup-2 Kafka plans.
[HH-5111](https://aiven.atlassian.net/browse/HH-5111)
[HH-5111]: https://aiven.atlassian.net/browse/HH-5111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: Datadog integration withdrawal for startup-2 plans

---

docs/products/clickhouse/get-started.md

https://aiven.atlassian.net/browse/DOC-1343

fix: k8 link in clickhouse get-started doc

---

docs/platform/howto/list-identity-providers.md

fix: IdP category title

---

docs/products/clickhouse/concepts/disaster-recovery.md
docs/products/clickhouse/reference/limitations.md

https://aiven.atlassian.net/browse/DDB-1405

feat: ClickHouse auto backup before powering off a service

---

docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md

The Iceberg community decided to change the location for the catalog concept: https://lists.apache.org/thread/jnfnf886r4y8q3og668f02pbw8ym7pq6

fix: Use updated Iceberg catalog page.

---

docs/platform/howto/manage-application-users.md
docs/platform/howto/manage-groups.md
docs/platform/howto/manage-project.md

update: standardize tab naming for TF samples

---

docs/platform/howto/integrations/prometheus-metrics.md

Prometheus client needs to have additional replica uri if multi node service has separate replica uri. Kafka is multi node service, but it does not have replica uri. For Kafka all nodes are behind one uri.

fix: Kafka services do not have replica uri

---

docs/products/kafka/howto/enable-governance.md

Clarify that both super admin and organization admin roles can enable governance.
https://aiven.atlassian.net/browse/GOV-667

update: clarify governance enabling permissions

---

docs/products/kafka/get-started.md
docs/products/kafka/kafka-connect/get-started.md
static/includes/terraform-apply-changes.md
static/includes/terraform-get-started-prerequisites.md

Replaces TF code with synced samples from the TF repository. Adds TF code to the Kafka Connect get started guide.

update: Kafka and Kafka Connect get started Terraform instructions

---

docs/platform/concepts/vpcs.md

https://aiven.atlassian.net/browse/DOC-1381

fix: AWS VPC URL typo 

---

docs/platform/howto/use-aws-privatelinks.md
docs/tools/cli/service/privatelink.md

https://aiven.atlassian.net/browse/DOC-1384

fix: privatelink doc improvements

---

docs/products/kafka/howto/terraform-governance-approvals.md

Update docs to use the external identity example from the Terraform repo.

update: use external identity example from TF repo

---

docs/platform/reference/eol-for-major-versions.md

Add Kafka 3.9 and note about KRaft to EOL major versions page.

update: EOL to include Kafka 3.9

---

docs/platform/howto/manage-bank-transfers.md
docs/platform/howto/use-billing-groups.md

update: add invoice emails to billing groups details

---

static/_redirects

update: redirect links to tf examples

---

docs/products/kafka/howto/rotate-credentials.md
sidebars.ts

Add documentation for rotating Apache Kafka service user credentials using the Console, including request, approval, and download steps.
https://aiven.atlassian.net/browse/GOV-1003
Preview - https://gov-1003-documentation-acces.aiven-docs.pages.dev/docs/products/kafka/howto/rotate-credentials

feat: Support credential rotation for Kafka subscriptions

---

docs/platform/howto/list-service.md

I'm not sure why this note exists in the page, but it was referencing M3DB which we do not offer anymore. 
The link in the note mentions clickhouse so I added a line in the section on clickhouse. I also added Aiven for AlloyDB Omni.

update: Remove m3db from timeseries note and add alloydb and clickhouse

---

docs/platform/reference/eol-for-major-versions.md

fix: service creation date

---

docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md

Support for Aiven for Apache Kafka® Connect secret providers is no longer a limitation.

update: remove limitations

---

docs/products/kafka/kafka-connect/howto/iceberg-sink-connector.md

Removed EA tag for Iceberg sink connector

update: Remove EA tag

---

static/code/products/valkey/connect.py

fix: incorrect variable in howto example

---

docs/platform/concepts/service-forking.md
docs/products/kafka/kafka-connect/concepts/list-of-connector-plugins.md

- Add Iceberg sink connector to the list of connectors
- Removed ElasticSearch connector as it is not longer supported 
- Removed ElasticSearch from the list of services to fork

update: add Iceberg sink connector to the list

---

docs/products/kafka/kafka-connect/howto/aws-glue-catalog.md
docs/products/kafka/kafka-connect/howto/aws-glue-rest-catalog.md

- Added missing configs from the AWS Glue REST example
- Added deprecation info about `sigv4-enabled: true`
- Fixed default and recommended value of `commit.timeout-ms`
- Made minor improvements to the user instructions and value formats

update: consolidate iceberg connector howto

---

static/_redirects

Migrate the legacy docs url redirect logic from NGINX reverse proxy on the aiven host level to docs's level using the couldflare redirect file.
Tested in staging with the same redirect logic
1. remove ending `.html`
`/index.html -> https://aiven.io/docs` 
eg: https://avnsmarketingtest.net/docs/index.html -> https://aiven.io/docs
2. remove double `/docs/docs`
`/docs/* -> https://aiven.io/docs/:splat`
eg: https://avnsmarketingtest.net/docs/docs/get-started -> https://aiven.io/docs/get-started
3. nested url, remove ending `index.html`
`/*/index.html -> https://aiven.io/docs/:splat`
eg: https://avnsmarketingtest.net/docs/get-started/index.html -> https://aiven.io/docs/get-started
4. remove ending `.html`
`/*.html ->  https://aiven.io/docs/:splat`
eg: …

feat: redirect support legacy url

---

docs/products/kafka/kafka-connect/howto/s3-sink-connector-aiven.md

Updated GitHub ref link for S3 sink connector.

update: GitHub link in S3 sink connector

---

docs/products/kafka/kafka-connect/howto/manage-connector-versions.md

Put it clearer that multi-version connectors refer
- to plugins available in several versions, where the selected plugin version sits at service-level
- not to the ability to run multiple instances of a given connector using different versions.

update: clarify multi-version connector capability

---

docs/platform/reference/eol-for-major-versions.md
docs/products/kafka/concepts/kraft-mode.md
docs/products/kafka/concepts/upgrade-procedure.md

Removed Early Access (EA) tag from KRaft-related documentation.
[HH-5372](https://aiven.atlassian.net/browse/HH-5372)
[HH-5372]: https://aiven.atlassian.net/browse/HH-5372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: remove EA tag for KRaft docs

---

docs/platform/concepts/authentication-tokens.md

fix: typo on tokens page

---

docs/products/kafka/kafka-connect/howto/cassandra-streamreactor-sink.md
docs/products/kafka/kafka-connect/howto/cassandra-streamreactor-source.md
docs/products/kafka/kafka-connect/howto/influx-sink.md
docs/products/kafka/kafka-connect/howto/mongodb-sink-lenses.md
docs/products/kafka/kafka-connect/howto/mqtt-sink-connector.md
docs/products/kafka/kafka-connect/howto/mqtt-source-connector.md
docs/products/kafka/kafka-connect/howto/redis-streamreactor-sink.md
static/includes/streamreactor-compatibility-note.md

Stream Reactor has been updated to version 9.0.2, which introduces standardized class and package names. This makes it incompatible with version 4.2.0 previously used on Aiven.
- Added a version compatibility snippet to affected pages
- Improved structure and flow to align with the documentation style guide

update: version 9.x compatibility note for Stream Reactor

---

docs/products/cassandra/concepts/cross-cluster-replication.md
docs/products/cassandra/howto/disable-cross-cluster-replication.md
docs/products/cassandra/howto/enable-cross-cluster-replication.md
docs/products/cassandra/howto/manage-cross-cluster-replication.md
docs/products/clickhouse/howto/list-integrations.md
docs/products/clickhouse/howto/manage-users-roles.md
docs/products/kafka/karapace/get-started.md
docs/products/kafka/karapace/howto/enable-karapace.md
docs/tools/terraform.md

update: change links from dev center to TF examples

---

docs/products/kafka/howto/kafka-klaw.md

Document `application.properties` file location for Klaw
- Added default file paths from the Klaw source repo
- Clarified path resolution in Kubernetes deployments
- Included `spring.config.location` override example

update: Content for connect Aiven Kafka and Klaw topic

---

docs/products/postgresql/howto/use-pg-audit-logging.md

https://aiven.atlassian.net/browse/BF-3374
[PREVIEW](https://bf-3374-doc-pgaudit-logs-ava.aiven-docs.pages.dev/docs/products/postgresql/howto/use-pg-audit-logging#access-your-logs)

fix: use opensearch for accessing pgaudit logs

---

docs/products/kafka/howto/enable-oidc.md

The value of `kafka.sasl_oauthbearer_sub_claim_name` must be a single string claim (e.g., `sub` or `oid`) as defined by the OIDC provider.

update: clarify claim must be a string

---

docs/products/kafka/howto/enable-oidc.md

Added a note to the OIDC config section to explain the new Kafka 4.0 system property requirement for JWKS endpoints. 
https://aiven.atlassian.net/browse/HH-5846

update: clarify Kafka 4.0 behavior for JWKS endpoint config in OIDC

---

static/_redirects

update: remove dev center from redirects

---

docs/products/mysql/howto/migrate-from-external-mysql.md
docs/products/postgresql/howto/migrate-aiven-db-migrate.md

[JIRA](https://aiven.atlassian.net/browse/BF-3460)
[PREVIEW](https://bf-3460-docs-fix-pg-migratio.aiven-docs.pages.dev/docs/products/postgresql/howto/migrate-aiven-db-migrate#display-the-migration-status-using-the-aiven-cli)

fix: command for displaying PG migration status

---

.github/vale/styles/config/vocabularies/Aiven/accept.txt
docs/products/kafka/howto/generate-avro-java-classes.md
docs/products/kafka/howto/generate-java-classes-from-schemas.md
docs/products/kafka/howto/generate-json-java-classes.md
docs/products/kafka/howto/generate-protobuf-java-classes.md
docs/products/kafka/howto/schema-registry.md
sidebars.ts

Adds documentation for generating Java classes from Avro, Protobuf, and JSON schemas for use with Kafka and Karapace.
Ref: [POD-1457](https://aiven.atlassian.net/browse/POD-1457)
Preview:  https://pod-1319-docs-new-documentat.aiven-docs.pages.dev/docs/products/kafka/howto/generate-java-classes-from-schemas
[POD-1457]: https://aiven.atlassian.net/browse/POD-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update: docs for Java class generation from Avro, Protobuf, and JSON schemas

---

docs/products/kafka/howto/generate-avro-java-classes.md

Add missing Confluent dependency for Avro schema serialization

update: Confluent dependency for Avro schema serialization

---

docs/products/kafka/howto/best-practices.md

Aiven leverages a cache to manage topics in Apache Kafka clusters. In order to guarantee the stability of the service through this cache, a maximum number of 7,000 topics is recommended. A user alert was also created to warn users about too many topics.

update: max number of topics per cluster

---

docs/products/opensearch/howto/jwt-authentication.md
docs/products/opensearch/howto/saml-sso-authentication.md
sidebars.ts

[JIRA](https://aiven.atlassian.net/browse/MA-3518)
[DOC PREVIEW
](https://ma-3518-docs-jwt-auth-suppor.aiven-docs.pages.dev/docs/products/opensearch/howto/jwt-authentication)

feat: JWT authentication for OpenSearch
